const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const script = fs.readFileSync(path.join(root, 'script.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'styles', 'monster-slots.css'), 'utf8');

assert.match(html, /class="battlefield-zone-label enemy-zone-label"/, 'enemy battlefield has a shared label');
assert.match(html, /id="player-battle-stage"/, 'player party has a shared battlefield display layer');
assert.match(html, /id="battle-player-art" class="battle-player-art hidden"/, 'main player returns to the unframed battlefield artwork');
assert.doesNotMatch(html, /portrait-prototype|combat-unit-frame|combat-unit-art/, 'battlefield markup no longer contains frame prototype elements');
assert.match(html, /id="player-stage-info"/, 'main player information floats near the battlefield art');
assert.match(html, /id="battle-companion-icons" class="battle-companion-icons hidden"/, 'battlefield provides a generic companion icon tray');
assert.match(html, /91e08ae1dc2e3a9906e05987484d36cae41f20cb\/styles\/monster-slots\.css/, 'battlefield loads the directional player attack animation');
assert.match(html, /87122db\/script\.js/, 'battlefield loads the elite-affix build');
assert.match(script, /--basic-lunge-x[\s\S]*deltaX \/ distance \* 24/, 'basic attacks calculate a short lunge toward the current target');
assert.match(script, /--basic-lunge-y[\s\S]*deltaY \/ distance \* 24/, 'basic attack lunge follows the target direction');
assert.match(script, /goblinTreasureChest:[\s\S]*artClass: 'goblin-treasure-chest-art'/, 'goblin treasure chest no longer uses goblin placeholder metadata');
assert.match(css, /@keyframes partyBasicStrike[\s\S]*translate\(var\(--basic-lunge-x, 24px\),var\(--basic-lunge-y, -8px\)\)/, 'player artwork lunges and returns without moving the surrounding HUD');
assert.doesNotMatch(html, /id="hunter-companion"/, 'legacy full-body hunter companion is removed from the battlefield');
assert.match(css, /grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/, 'desktop enemies share a four-unit battlefield row');
assert.match(css, /#enemy-squad \.monster-battle-slot[\s\S]*?border: 0 !important;[\s\S]*?background: none !important;/, 'individual monster cards have no frame or background');
assert.match(css, /\.monster-battle-slot\.elite,[\s\S]*?\.monster-battle-slot\.boss \{ --unit-rank-scale: 1\.08; \}/, 'boss and elite monsters share the same modest rank scale');
assert.match(css, /top: 16% !important;/, 'desktop enemy formation moves closer to the player formation');
assert.match(css, /\.battle-field \.player-stage-info \{ left: 50%; translate: -50% 0; \}/, 'main player information follows the player art horizontally');
assert.match(css, /\.battle-field \.player-grounding \{[\s\S]*?background: rgba\(0, 0, 0, \.28\) !important;/, 'main player has a subtle grounding shadow');
assert.match(css, /\.battle-field \.player-stage-info,[\s\S]*?\.battle-field \.player-stage-floating \{[\s\S]*?display: none !important;/, 'main and party vitals are hidden over battlefield units');
assert.match(css, /\.battle-field \.player-stage-art \{[\s\S]*?scale: 1\.28;/, 'party art is optically enlarged to match the main player');
assert.match(css, /body:has\(\.battle-screen:not\(\.hidden\)\) \.toast \{[\s\S]*?right: calc\(var\(--battle-right-column, 15%\) \+ 18px\) !important;[\s\S]*?left: auto !important;/, 'battle loot notifications align to the right of the battlefield');
assert.match(css, /\.battle-field \.battle-companion-icons \{[\s\S]*?right: 18px;[\s\S]*?bottom: 112px;[\s\S]*?flex-wrap: wrap-reverse;/, 'companion icons occupy an extensible tray above the right-side notification area');
assert.match(css, /\.battle-field \.battle-companion-icon \{[\s\S]*?width: 54px;[\s\S]*?height: 54px;/, 'companions render as compact icons');
assert.match(script, /const activeBattleCompanions = character\.job === 'hunter'[\s\S]*?companionIcons\.innerHTML = activeBattleCompanions\.map/, 'generic companion collection renders the currently active hunter companion');
assert.match(script, /human: \{ image: 'assets\/companion-human-hunter\.png', icon: 'assets\/hunter-companion-human-icon\.png', portrait: true/, 'human hunters use the supplied dog portrait');
assert.match(script, /elf: \{ image: 'assets\/companion-elf\.png', icon: 'assets\/hunter-companion-elf-icon\.png', portrait: true/, 'elf hunters use the supplied moon cat portrait');
assert.match(script, /racialCompanion\.icon \|\| racialCompanion\.image/, 'companion tray prefers portrait artwork while retaining a safe fallback');
assert.match(css, /\.battle-companion-icon\.portrait \{[\s\S]*?background-position: center;[\s\S]*?background-size: cover;/, 'dedicated portraits preserve their complete framed composition');
assert.doesNotMatch(script, /companionName\.textContent/, 'companion tray does not add level, health, stats, or text panels');
assert.match(css, /\.player-battle-stage[\s\S]*?justify-content: center;/, 'party units auto-center on their shared ground');
assert.match(script, /battleCharacterArt\[`\$\{member\.character\.race\}:\$\{member\.character\.job\}`\]/, 'party display reuses existing character art');
assert.doesNotMatch(script, /portraitPrototypeAssigned|normal-portrait-prototype|player-unit-frame/, 'battlefield rendering no longer assigns frame classes');
assert.doesNotMatch(css, /portrait-prototype|combat-frame-width|player-frame-width|gold dragon frame/, 'combat frame styling is fully removed');
assert.match(script, /battlePlayerArt\.style\.backgroundImage = characterArt \? `url\('\$\{characterArt\}'\)` : '';/, 'unframed main player receives its character artwork directly');
assert.doesNotMatch(script, /battlePlayerArt\.querySelector\('\.combat-unit-art'\)/, 'main player no longer depends on the removed frame artwork node');
assert.match(css, /0\.6\.16: invisible unit zones[\s\S]*?--unit-scale-small: \.9;[\s\S]*?--unit-scale-humanoid: 1;[\s\S]*?--unit-scale-beast: 1\.12;[\s\S]*?--unit-scale-large: 1\.22;/, 'four invisible unit-zone size tiers normalize monster bodies');
assert.match(css, /#enemy-squad \.monster-battle-slot \{[\s\S]*?border: 0 !important;[\s\S]*?background: none !important;[\s\S]*?box-shadow: none !important;/, 'monster unit zones remain visually frameless');
assert.match(css, /#enemy-squad \.monster-slot-header \{[\s\S]*?justify-self: center !important;[\s\S]*?width: auto !important;[\s\S]*?border-radius: 999px !important;/, 'monster names use compact attached labels instead of wide cards');
assert.match(css, /#enemy-squad \.monster-slot-hp \{[\s\S]*?top: -4px !important;[\s\S]*?width: 72% !important;/, 'monster health bars sit directly beneath their artwork');
assert.match(css, /height: 37% !important;[\s\S]*?bottom: 8% !important;/, 'desktop main player is enlarged and raised within the ally field');
assert.match(css, /0\.6\.17: widen only the main character silhouette[\s\S]*?scale: calc\(var\(--character-scale, 1\) \* 1\.1\) var\(--character-scale, 1\) !important;/, 'main character widens ten percent without increasing its height');
assert.match(css, /0\.6\.18: every monster uses one visual scale[\s\S]*?--unit-scale-small: 1;[\s\S]*?--unit-scale-humanoid: 1;[\s\S]*?--unit-scale-beast: 1;[\s\S]*?--unit-scale-large: 1;/, 'all monster body categories use one visual scale');
assert.match(css, /monster-battle-slot\.elite,[\s\S]*?monster-battle-slot\.boss \{[\s\S]*?--unit-rank-scale: 1;/, 'elite and boss ranks no longer enlarge monster artwork');
assert.match(css, /monster-battle-slot\.rare \.monster-image-frame::after,[\s\S]*?monster-battle-slot\.elite \.monster-image-frame::after,[\s\S]*?monster-battle-slot\.boss \.monster-image-frame::after[\s\S]*?border-radius: 50%;/, 'rare, elite and boss monsters receive rank auras');
assert.match(css, /monster-battle-slot\.rare \{[\s\S]*?93, 190, 255[\s\S]*?monster-battle-slot\.elite \{[\s\S]*?174, 116, 255[\s\S]*?monster-battle-slot\.boss \{[\s\S]*?255, 194, 73/, 'special ranks use distinct blue, purple and gold aura colors');
assert.match(script, /function getMonsterVisualSize\(enemy = \{\}\)/, 'monster visual sizing uses a reusable category resolver');
assert.doesNotMatch(script, /if \(enemy\.isBoss\) return 'boss';/, 'boss rank does not replace the creature body-size category');
assert.match(script, /class="enemy-unit monster-battle-slot visual-size-\$\{visualSize\}/, 'enemy slots expose their visual-size category to CSS');
assert.match(script, /data-visual-size="humanoid" data-member-id=/, 'party players share the humanoid visual baseline');
assert.match(css, /--unit-scale-small: \.8;[\s\S]*?--unit-scale-humanoid: \.92;[\s\S]*?--unit-scale-beast: 1\.3;[\s\S]*?--unit-scale-large: 1\.25;/, 'desktop visual-body scale preserves creature body-size categories');
assert.match(css, /visual-size-humanoid \.monster-slot-image \{ scale: calc\(var\(--unit-scale-humanoid\) \* var\(--unit-art-correction, 1\) \* var\(--unit-rank-scale\)\) !important; \}/, 'humanoid size combines body, asset, and modest rank corrections');
assert.match(script, /const monsterVisualScaleCorrections = \{[\s\S]*?plainsRabbit: 1\.15/, 'unusual transparent padding can be corrected per monster asset');
assert.match(script, /enemy\.visualScaleCorrection \|\| monsterVisualScaleCorrections\[enemy\.id\] \|\| 1/, 'future monster definitions can provide their own visual correction');
assert.match(css, /\[class\*="visual-size-"\] \.monster-slot-image \{[\s\S]*?transform-origin: center bottom;/, 'category scaling preserves every monster foot baseline');
assert.match(script, /其餘 \$\{reserveCount\}/, 'overflow enemies are not described as a front or back row');
assert.match(script, /data-member-id="\$\{member\.id\}"/, 'party battlefield units have stable animation targets');
assert.match(script, /playPartyMemberCombatAnimation\(member,[\s\S]*?kind: 'skill', skillName: skill\.name/, 'skills animate every party member and expose the skill name');
assert.match(script, /playPartyMemberCombatAnimation\(member, \[targetIndex\], \{ kind: 'basic' \}\)/, 'basic attacks animate every party member');
assert.match(script, /function battleCharacterActionArt|const battleCharacterActionArt/, 'battlefield resolves dedicated character action artwork');
assert.match(script, /back-\$\{action\}\.png/, 'idle, attack, and hit states share a predictable asset convention');
assert.match(script, /assets\/character-actions/, 'battlefield uses normalized transparent action assets');
assert.match(script, /setBattleCharacterAction\(art, member\.character, 'attack'\)/, 'party attacks swap to their attack artwork');
assert.match(script, /playPartyMemberHitAnimation\(target\)/, 'enemy damage swaps the targeted party member to hit artwork');
assert.match(css, /@keyframes characterActionHit/, 'hit artwork receives a short impact animation');
assert.match(css, /\.character-attack-effect\.attack-kind-skill::after/, 'skill attacks show an in-field skill label');
assert.match(css, /prefers-reduced-motion: reduce/, 'combat animation respects reduced-motion preferences');
assert.match(css, /#battle-player-art\[aria-label\][\s\S]*?width: clamp\(80px, 10vw, 133px\) !important;[\s\S]*?height: 24\.5% !important;/, 'main player uses the same desktop unit box as party members');
assert.match(css, /@media \(max-width: 700px\)[\s\S]*?#battle-player-art\[aria-label\][\s\S]*?width: clamp\(58px, 18vw, 78px\) !important;[\s\S]*?height: 22% !important;/, 'main player uses the same mobile unit box as party members');
assert.match(css, /\.player-battle-stage[\s\S]*?height: 24\.5%;/, 'party member stage is reduced to about seventy percent of its previous height');
assert.match(css, /\.battle-field \{ --player-unit-ground-line: 7%; \}[\s\S]*?\.player-battle-stage,[\s\S]*?#battle-player-art\[aria-label\],[\s\S]*?\.player-grounding \{[\s\S]*?bottom: var\(--player-unit-ground-line\) !important;/, 'all desktop player units share an inset ground line inside the ally field');
assert.match(css, /@media \(max-width: 700px\) \{[\s\S]*?--player-unit-ground-line: 6%;/, 'mobile player units also retain space above the ally field edge');
assert.match(css, /data-count="3"[\s\S]*?nth-child\(3\)[\s\S]*?left: 74%;/, 'desktop formation reserves distinct centered positions for four total players');
assert.match(css, /@media \(max-width: 700px\)[\s\S]*?data-count="3"[\s\S]*?nth-child\(3\)[\s\S]*?left: 81%;/, 'mobile formation reserves distinct positions for four total players');
assert.doesNotMatch(html, /data-menu-action="材料"/, 'materials no longer duplicate the backpack in the battle menu');
assert.doesNotMatch(script, /button\.dataset\.menuAction === '材料'/, 'the removed material shortcut has no stale click handler');
assert.match(css, /grid-template-columns: repeat\(7, minmax\(0, 1fr\)\) !important;/, 'the seven remaining battle actions share the full row');
assert.match(css, /body:has\(\.battle-screen:not\(\.hidden\)\) \.toast[\s\S]*?bottom: calc\(92px/, 'battle loot notifications sit above the action bar');
assert.match(script, /<main class="drop-lookup-simple">/, 'drop lookup uses a simple item-list layout');
assert.doesNotMatch(script, /data-drop-map=|data-drop-travel=|drop-source-list/, 'drop lookup does not render map sources or travel actions');
assert.match(script, /<article class="drop-result-card">[\s\S]*?item\.name[\s\S]*?item\.typeLabel/, 'drop cards only show the item identity and type');

console.log('battlefield UI integration: assertions passed');
