const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const script = fs.readFileSync(path.join(root, 'script.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'styles', 'monster-slots.css'), 'utf8');
const layoutCss = fs.readFileSync(path.join(root, 'styles', 'mmorpg-layout.css'), 'utf8');

assert.match(html, /id="player-battle-stage"/, 'party players render on the battlefield');
assert.match(html, /id="battle-player-art" class="battle-player-art hidden"/, 'main player has a dedicated portrait node');
assert.match(html, /styles\/monster-slots\.css\?v=20260821-piercing-shot-v1/, 'battlefield loads the current local portrait styles');
assert.match(html, /script\.js\?v=20260821-piercing-shot-v1/, 'battlefield loads the current local combat logic');
assert.match(script, /return battleCharacterArt\[`\$\{character\.race\}:\$\{character\.job\}`\] \|\| '';/, 'battle uses stable front character artwork');
assert.match(script, /'orc:warrior': 'assets\/character-portraits\/orc-warrior\.png'/, 'orc warrior uses the supplied portrait');
assert.match(script, /'orc:hunter': 'assets\/character-portraits\/orc-hunter\.png'/, 'orc hunter uses the supplied portrait');
assert.match(script, /'orc:assassin': 'assets\/character-portraits\/orc-assassin\.png'/, 'orc rogue uses the supplied portrait');
assert.match(script, /'orc:mage': 'assets\/character-portraits\/orc-mage\.png'/, 'orc mage uses the supplied portrait');
assert.match(script, /'undead:warrior': 'assets\/character-portraits\/undead-warrior\.png'/, 'undead warrior uses the supplied portrait');
assert.match(script, /'undead:hunter': 'assets\/character-portraits\/undead-hunter\.png'/, 'undead hunter uses the supplied portrait');
assert.match(script, /'undead:assassin': 'assets\/character-portraits\/undead-assassin\.png'/, 'undead rogue uses the supplied portrait');
assert.match(script, /'undead:mage': 'assets\/character-portraits\/undead-mage\.png'/, 'undead mage uses the supplied portrait');
assert.match(script, /'undead:priest': 'assets\/character-portraits\/undead-priest\.png'/, 'undead priest uses the supplied portrait');
assert.match(script, /'elf:warrior': 'assets\/character-portraits\/elf-warrior\.png'/, 'night elf warrior uses the supplied portrait');
assert.match(script, /'elf:hunter': 'assets\/character-portraits\/elf-hunter\.png'/, 'night elf hunter uses the supplied portrait');
assert.match(script, /'elf:assassin': 'assets\/character-portraits\/elf-assassin\.png'/, 'night elf rogue uses the supplied portrait');
assert.match(script, /'elf:mage': 'assets\/character-portraits\/elf-mage\.png'/, 'night elf mage uses the supplied portrait');
assert.match(script, /'human:warrior': 'assets\/character-portraits\/human-warrior\.png'/, 'human warrior uses the supplied portrait');
assert.match(script, /'human:hunter': 'assets\/character-portraits\/human-hunter\.png'/, 'human hunter uses the supplied portrait');
assert.match(script, /'human:assassin': 'assets\/character-portraits\/human-assassin\.png'/, 'human rogue uses the supplied portrait');
assert.match(script, /'human:mage': 'assets\/character-portraits\/human-mage\.png'/, 'human mage uses the supplied portrait');
assert.match(script, /'human:priest': 'assets\/character-portraits\/human-priest\.png'/, 'human priest uses the supplied portrait');
assert.doesNotMatch(script, /assets\/character-actions/, 'legacy idle and attack action sheets are removed');
assert.doesNotMatch(script, /character-attack-effect|--attack-travel-x|--basic-lunge-x/, 'shared attack effects are removed');
assert.doesNotMatch(layoutCss, /character-attack-effect|characterAttackProjectile|attack-effect-/, 'legacy shared attack effect styles are removed');

assert.match(css, /--player-portrait-size: clamp\(64px, 7\.2vw, 92px\)/, 'desktop portraits use one compact size');
assert.match(css, /Final 0\.7\.1 battlefield composition[\s\S]*?--enemy-formation-top: calc\(3% \+ 24px\);[\s\S]*?--enemy-formation-height: 31%;/, 'desktop enemy formation leaves most of the battlefield background visible');
assert.match(css, /Final 0\.7\.1 battlefield composition[\s\S]*?@media \(min-width: 701px\)[\s\S]*?data-count="3"[\s\S]*?left: 14%[\s\S]*?left: 38%[\s\S]*?left: 62%[\s\S]*?left: 86%/, 'four desktop player portraits use evenly separated anchors');
assert.match(css, /Final 0\.7\.1 battlefield composition[\s\S]*?@media \(max-width: 700px\)[\s\S]*?--enemy-formation-height: 35%;[\s\S]*?--player-portrait-size: clamp\(48px, 14vw, 64px\)/, 'mobile keeps both formations compact');
assert.match(css, /Final 0\.7\.1 battlefield composition[\s\S]*?data-count="3"[\s\S]*?left: 20%[\s\S]*?left: 41%[\s\S]*?left: 61%[\s\S]*?left: 81%/, 'four mobile portraits retain non-overlapping anchors');
assert.match(css, /overflow: hidden !important;[\s\S]*?border: 3px solid #d9a93f !important;[\s\S]*?border-radius: 50% !important;/, 'player artwork is clipped inside a gold circle');
assert.match(css, /@keyframes playerBasicShake/, 'basic attacks shake the portrait');
assert.match(script, /art\.classList\.remove\('is-attacking', 'is-target-skill', 'is-area-skill', 'is-heavy-strike', 'is-whirlwind', 'is-charge', 'is-power-shot', 'is-multi-shot', 'is-piercing-shot'\);[\s\S]*?void art\.offsetWidth;[\s\S]*?art\.classList\.add\(actionClass\);/, 'every attack reliably restarts its portrait animation');
assert.doesNotMatch(script, /classList\.(?:add|remove)\('attack'/, 'combat no longer activates the legacy attack class');
assert.doesNotMatch(layoutCss, /characterAttackWarrior|characterAttackAssassin|characterAttackHunter|characterAttackMage|characterAttackPriest/, 'legacy per-job attack motion is removed');
assert.match(script, /skillId === 'charge' \? 'is-charge' : skillId === 'power-shot' \? 'is-power-shot'/, 'named skill presets select distinct movement types');
assert.match(script, /kind === 'skill' && !area[\s\S]*?document\.querySelector\(`#enemy-\$\{targetIndexes\[0\]\}`\)/, 'only single-target skills resolve their actual target element');
assert.match(script, /targetRect \? targetRect\.left \+ targetRect\.width \* \.5/, 'single-target destination uses target position');
assert.match(script, /style\.setProperty\('--skill-move-y'[\s\S]*?fighter\?\.classList\.add\(actionClass\);[\s\S]*?art\.classList\.add\(actionClass\);/, 'target coordinates are ready before the skill animation starts');
assert.doesNotMatch(script.match(/function playPartyMemberCombatAnimation[\s\S]*?function playCompanionAttackAnimation/)?.[0] || '', /oldestAliveEnemyIndex\(\)/, 'single-target animation never substitutes the oldest or first enemy');
assert.match(script, /fieldRect\.left \+ fieldRect\.width \* \.5/, 'area skills use the battlefield center');
assert.match(script, /area: Number\(skillEffect\.targets \|\| skill\.targets \|\| 1\) > 1/, 'target count selects area movement');
assert.match(script, /kind === 'skill' && area[\s\S]*?document\.querySelector\('#enemy-squad'\)/, 'area skills resolve the enemy formation instead of one monster');
assert.match(script, /enemyFormationRect\.left \+ enemyFormationRect\.width \* \.5/, 'area skills use the enemy formation horizontal center');
assert.match(script, /enemyFormationRect\.bottom \+ artRect\.height \* \.2/, 'area skills stop just in front of the enemy formation');
assert.match(script, /const target = kind === 'skill' && !area/, 'area skills never bind their travel to an individual target');
assert.match(css, /@keyframes playerSkillTravel[\s\S]*?--skill-move-x[\s\S]*?--skill-move-y/, 'skills travel out and return');
assert.match(script, /battleSkillEffectPresets[\s\S]*?'heavy-strike'[\s\S]*?duration: 680[\s\S]*?impactAt: 350/, 'heavy strike is a reusable short battle-effect preset');
assert.match(script, /captureBattleTargetAnchor\(index\)[\s\S]*?getBoundingClientRect/, 'heavy strike captures its actual target position before damage resolves');
assert.match(script, /followTarget[\s\S]*?`#enemy-\$\{targetAnchor\.index\}`[\s\S]*?requestAnimationFrame\(followTarget\)/, 'active heavy strike effects follow the selected target');
assert.match(script, /effect\.remove\(\);[\s\S]*?if \(!layer\.childElementCount\) layer\.remove\(\)/, 'finished skill effects leave no stale effect DOM');
assert.match(script, /showDamage: !\['heavy-strike', 'whirlwind', 'charge', 'power-shot', 'multi-shot', 'piercing-shot'\]\.includes\(skill\.id\)/, 'skill presets suppress early generic damage numbers when impact timing is custom');
assert.match(script, /visualStunAt = now \+ 550/, 'stun art waits until the impact animation finishes');
assert.match(script, /Date\.now\(\) < enemySkillState\.stunnedUntil[\s\S]*?enemySkillState\.visualStunAt/, 'stun stars are driven by the actual stun state');
assert.match(css, /impact-shockwave[\s\S]*?var\(--target-width\) \* 1\.42/, 'single-target shockwave stays proportional to the target');
assert.match(css, /impact-debris[\s\S]*?heavyDebris/, 'heavy strike has a restrained debris burst');
assert.match(css, /@keyframes playerHeavyStrikeLunge/, 'heavy strike uses a short portrait lunge and return');
assert.match(script, /whirlwind: \{ duration: 1000, impactAt: 350, className: 'battle-effect-whirlwind' \}/, 'whirlwind is a reusable one-second battle-effect preset');
assert.match(script, /targets: hits\.map\(\(target\) => \(\{ index: target\.index, damage: target\.result\.finalDamage, anchor: targetAnchors\.get\(target\.index\) \}\)\)/, 'whirlwind binds each hit visual and number to its resolved target');
assert.match(script, /showDamage: !\['heavy-strike', 'whirlwind', 'charge', 'power-shot', 'multi-shot', 'piercing-shot'\]\.includes\(skill\.id\)/, 'preset damage numbers wait for their custom hit visuals');
assert.match(css, /whirlwind-target-hit[\s\S]*?var\(--hit-order\) \* \.05s/, 'whirlwind staggers target slashes by fifty milliseconds');
assert.match(css, /whirlwind-afterimages[\s\S]*?whirlwindAfterimage/, 'whirlwind uses portrait afterimages as its signature');
assert.match(css, /whirlwind-finisher[\s\S]*?\.7s/, 'whirlwind ends with a larger arc slash');
assert.doesNotMatch(css.match(/\.battle-effect-whirlwind[\s\S]*?@keyframes whirlwindFinisher/)?.[0] || '', /debris|crack|fire|explosion/, 'whirlwind does not reuse heavy-strike debris or ground cracks');
assert.match(script, /charge: \{ duration: 780, impactAt: 400, className: 'battle-effect-charge' \}/, 'charge is a reusable short single-target preset');
assert.match(script, /stopShort[\s\S]*?--charge-move-x[\s\S]*?--charge-pull-x/, 'charge pulls back then stops in front of its actual target');
assert.match(script, /skill\.id === 'charge'[\s\S]*?playBattleSkillEffect\(skill\.id, targetAnchors\.get\(displayedTarget\.index\)/, 'charge visuals bind to the resolved single target');
assert.match(css, /charge-cone[\s\S]*?clip-path:polygon/, 'charge impact uses a forward cone rather than a radial explosion');
assert.match(script, /mainChargeBuffActive[\s\S]*?skillHasteUntil[\s\S]*?has-charge-buff/, 'charge buff art follows the real buff end time');
assert.doesNotMatch(css.match(/\.battle-effect-charge[\s\S]*?@keyframes chargeBuffFlow/)?.[0] || '', /debris|crack/, 'charge does not reuse heavy-strike debris or cracks');
assert.match(script, /'power-shot': \{ duration: 760, impactAt: 400, className: 'battle-effect-power-shot' \}/, 'power shot is a reusable short single-target preset');
assert.match(script, /captureBattleAttackerAnchor[\s\S]*?--arrow-start-x/, 'power shot draws a projectile from the hunter to the resolved target');
assert.match(script, /visualSlowAt = now \+ 550[\s\S]*?visualMarkAt = now \+ 550/, 'power-shot statuses appear after the impact burst');
assert.match(script, /Date\.now\(\) < enemySkillState\.slowedUntil[\s\S]*?Date\.now\(\) < enemySkillState\.markedUntil/, 'slow and hunter mark visuals follow their real status timers');
assert.match(css, /power-shot-arrow::after[\s\S]*?border-left:14px solid/, 'power shot keeps a visible physical arrowhead');
assert.match(css, /enemy-slow-airflow/, 'power shot shows restrained slow airflow');
assert.match(css, /enemy-hunter-mark/, 'advanced power shot shows a distinct hunter mark');
assert.match(script, /'multi-shot': \{ duration: 880, impactAt: 450, className: 'battle-effect-multi-shot' \}/, 'multi shot is a reusable sub-second projectile preset');
assert.match(script, /resolvedTargets\.map[\s\S]*?targetAnchors\.get\(target\.index\)/, 'multi shot creates projectiles only for the resolved target list');
assert.match(script, /data-effect-target="\$\{target\.index\}"[\s\S]*?--hit-x:[\s\S]*?--hit-y:/, 'every multi-shot projectile owns its target coordinates');
assert.match(script, /querySelectorAll\('\[data-effect-target\]'\)[\s\S]*?getBoundingClientRect/, 'active projectiles track target layout changes');
assert.match(css, /multi-shot-projectile::after[\s\S]*?border-left:13px solid/, 'multi shot uses visible physical arrowheads');
assert.match(css, /var\(--hit-order\)\*\.04s/, 'multi-shot impacts stagger by forty milliseconds');
assert.doesNotMatch(css.match(/\.battle-effect-multi-shot[\s\S]*?@keyframes multiShotDamage/)?.[0] || '', /explosion|crack|debris|fire/, 'multi shot stays visually distinct from explosions and heavy impacts');
assert.match(script, /'piercing-shot': \{ duration: 960, impactAt: 400, className: 'battle-effect-piercing-shot' \}/, 'piercing shot is a reusable one-second projectile preset');
assert.match(script, /function animatePiercingProjectile[\s\S]*?const arrow = effect\.querySelector\('\.piercing-shot-arrow'\)/, 'piercing shot creates one main projectile');
assert.match(script, /points = \[origin, \.\.\.targets\.map[\s\S]*?points\.push/, 'one projectile traverses all selected hit points then exits');
assert.match(script, /resolvedTargets\.slice\(0, 4\)/, 'piercing visuals never exceed four resolved targets');
assert.match(css, /piercing-shot-hit[\s\S]*?piercingCross[\s\S]*?piercingArmor/, 'each piercing target gets a cross flash and temporary armor-break mark');
assert.doesNotMatch(css.match(/\.battle-effect-piercing-shot[\s\S]*?@keyframes piercingDamage/)?.[0] || '', /explosion|fire|debris|crack/, 'piercing shot avoids explosions and persistent debris');

assert.match(script, /class="enemy-unit monster-battle-slot visual-size-\$\{visualSize\}/, 'monsters keep full-body image slots');
assert.match(css, /monster-battle-slot\.elite,[\s\S]*?monster-battle-slot\.boss \{[\s\S]*?--unit-rank-scale: 1;/, 'elite and boss monsters are not enlarged');
assert.match(css, /monster-battle-slot\.elite \{[\s\S]*?174, 116, 255[\s\S]*?monster-battle-slot\.boss \{[\s\S]*?255, 194, 73/, 'rank auras remain distinct');
assert.match(css, /prefers-reduced-motion: reduce/, 'combat movement respects reduced-motion settings');

console.log('battlefield UI integration: assertions passed');
