const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const script = fs.readFileSync(path.join(root, 'script.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'styles', 'monster-slots.css'), 'utf8');

assert.match(html, /class="battlefield-zone-label enemy-zone-label"/, 'enemy battlefield has a shared label');
assert.match(html, /id="player-battle-stage"/, 'player party has a shared battlefield display layer');
assert.match(html, /id="player-stage-info"/, 'main player information floats near the battlefield art');
assert.match(html, /id="battle-companion-icons" class="battle-companion-icons hidden"/, 'battlefield provides a generic companion icon tray');
assert.doesNotMatch(html, /id="hunter-companion"/, 'legacy full-body hunter companion is removed from the battlefield');
assert.match(css, /grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/, 'desktop enemies share a four-unit battlefield row');
assert.match(css, /#enemy-squad \.monster-battle-slot[\s\S]*?border: 0 !important;[\s\S]*?background: none !important;/, 'individual monster cards have no frame or background');
assert.match(css, /\.monster-battle-slot\.elite,[\s\S]*?\.monster-battle-slot\.boss \{ --unit-rank-scale: 1\.08; \}/, 'boss and elite monsters share the same modest rank scale');
assert.match(css, /top: 16% !important;/, 'desktop enemy formation moves closer to the player formation');
assert.match(css, /\.battle-field \.player-stage-info \{ left: 50%; translate: -50% 0; \}/, 'main player information follows the player art horizontally');
assert.match(css, /\.battle-field \.player-grounding \{[\s\S]*?background: rgba\(0, 0, 0, \.28\) !important;/, 'main player has a subtle grounding shadow');
assert.match(css, /\.battle-field \.player-stage-info,[\s\S]*?\.battle-field \.player-stage-floating \{[\s\S]*?display: none !important;/, 'main and party vitals are hidden over battlefield units');
assert.match(css, /\.battle-field \.player-stage-art \{[\s\S]*?scale: 1\.28;/, 'party art is optically enlarged to match the main player');
assert.match(css, /body:has\(\.battle-screen:not\(\.hidden\)\) \.toast \{[\s\S]*?right: calc\(var\(--battle-right-column, 15%\) \+ 18px\) !important;[\s\S]*?left: auto !important;/, 'battle loot notifications align to the right of the battlefield');
assert.match(css, /\.battle-field \.battle-companion-icons \{[\s\S]*?right: 18px;[\s\S]*?bottom: 112px;[\s\S]*?flex-wrap: wrap-reverse;/, 'companion icons occupy an extensible tray above the right-side notification area');
assert.match(css, /\.battle-field \.battle-companion-icon \{[\s\S]*?width: 54px;[\s\S]*?height: 54px;/, 'companions render as compact icons');
assert.match(script, /const activeBattleCompanions = character\.job === 'hunter'[\s\S]*?companionIcons\.innerHTML = activeBattleCompanions\.map/, 'generic companion collection renders the currently active hunter companion');
assert.match(script, /human: \{ image: 'assets\/companion-human-hunter\.png', icon: 'assets\/hunter-companion-human-icon\.png', portrait: true/, 'human hunters use the supplied dog portrait');
assert.match(script, /elf: \{ image: 'assets\/companion-elf\.png', icon: 'assets\/hunter-companion-elf-icon\.png', portrait: true/, 'elf hunters use the supplied moon cat portrait');
assert.match(script, /orc: \{ image: 'assets\/companion-orc\.png', icon: 'assets\/hunter-companion-orc-icon\.png', portrait: true/, 'orc hunters use the supplied war wolf portrait');
assert.match(script, /undead: \{ image: 'assets\/companion-undead\.png', icon: 'assets\/hunter-companion-undead-icon\.png', portrait: true/, 'undead hunters use the supplied spectral hound portrait');
assert.match(script, /racialCompanion\.icon \|\| racialCompanion\.image/, 'companion tray prefers portrait artwork while retaining a safe fallback');
assert.match(css, /\.battle-companion-icon\.portrait \{[\s\S]*?background-position: center;[\s\S]*?background-size: cover;/, 'dedicated portraits preserve their complete framed composition');
assert.doesNotMatch(script, /companionName\.textContent/, 'companion tray does not add level, health, stats, or text panels');
assert.match(css, /\.player-battle-stage[\s\S]*?justify-content: center;/, 'party units auto-center on their shared ground');
assert.match(script, /battleCharacterArt\[`\$\{member\.character\.race\}:\$\{member\.character\.job\}`\]/, 'party display reuses existing character art');
assert.match(script, /function getMonsterVisualSize\(enemy = \{\}\)/, 'monster visual sizing uses a reusable category resolver');
assert.doesNotMatch(script, /if \(enemy\.isBoss\) return 'boss';/, 'boss rank does not replace the creature body-size category');
assert.match(script, /class="enemy-unit monster-battle-slot visual-size-\$\{visualSize\}/, 'enemy slots expose their visual-size category to CSS');
assert.match(script, /data-visual-size="humanoid" data-member-id=/, 'party players share the humanoid visual baseline');
assert.match(css, /--unit-scale-small: \.8;[\s\S]*?--unit-scale-humanoid: \.92;[\s\S]*?--unit-scale-beast: 1\.3;[\s\S]*?--unit-scale-large: 1\.25;/, 'desktop visual-body scale preserves creature body-size categories');
assert.match(css, /visual-size-humanoid \.monster-slot-image \{ scale: calc\(var\(--unit-scale-humanoid\) \* var\(--unit-art-correction, 1\) \* var\(--unit-rank-scale\)\) !important; \}/, 'humanoid size combines body, asset, and modest rank corrections');
assert.match(script, /const monsterVisualScaleCorrections = \{[\s\S]*?plainsRabbit: 1\.15/, 'unusual transparent padding can be corrected per monster asset');
assert.match(script, /enemy\.visualScaleCorrection \|\| monsterVisualScaleCorrections\[enemy\.id\] \|\| 1/, 'future monster definitions can provide their own visual correction');
assert.match(css, /\[class\*="visual-size-"\] \.monster-slot-image \{[\s\S]*?transform-origin: center bottom;/, 'category scaling preserves every monster foot baseline');
assert.match(script, /其餘 \$\{reserveCount\}/, 'overflow enemies are not described as a front or back row');
assert.match(script, /data-member-id="\$\{member\.id\}"/, 'party battlefield units have stable animation targets');
assert.match(script, /playPartyMemberCombatAnimation\(member,[\s\S]*?kind: 'skill', skillName: skill\.name/, 'skills animate every party member and expose the skill name');
assert.match(script, /playPartyMemberCombatAnimation\(member, \[targetIndex\], \{ kind: 'basic' \}\)/, 'basic attacks animate every party member');
assert.match(css, /\.character-attack-effect\.attack-kind-skill::after/, 'skill attacks show an in-field skill label');
assert.match(css, /prefers-reduced-motion: reduce/, 'combat animation respects reduced-motion preferences');
assert.match(css, /#battle-player-art\[aria-label\][\s\S]*?width: clamp\(80px, 10vw, 133px\) !important;[\s\S]*?height: 24\.5% !important;/, 'main player uses the same desktop unit box as party members');
assert.match(css, /@media \(max-width: 700px\)[\s\S]*?#battle-player-art\[aria-label\][\s\S]*?width: clamp\(58px, 18vw, 78px\) !important;[\s\S]*?height: 22% !important;/, 'main player uses the same mobile unit box as party members');
assert.match(css, /\.player-battle-stage[\s\S]*?height: 24\.5%;/, 'party member stage is reduced to about seventy percent of its previous height');
assert.match(css, /\.battle-field \{ --player-unit-ground-line: 7%; \}[\s\S]*?\.player-battle-stage,[\s\S]*?#battle-player-art\[aria-label\],[\s\S]*?\.player-grounding \{[\s\S]*?bottom: var\(--player-unit-ground-line\) !important;/, 'all desktop player units share an inset ground line inside the ally field');
assert.match(css, /@media \(max-width: 700px\) \{[\s\S]*?--player-unit-ground-line: 6%;/, 'mobile player units also retain space above the ally field edge');
assert.match(css, /data-count="3"[\s\S]*?nth-child\(3\)[\s\S]*?left: 74%;/, 'desktop formation reserves distinct centered positions for four total players');
assert.match(css, /@media \(max-width: 700px\)[\s\S]*?data-count="3"[\s\S]*?nth-child\(3\)[\s\S]*?left: 81%;/, 'mobile formation reserves distinct positions for four total players');
assert.doesNotMatch(html, /data-menu-action="材料"/, 'materials no longer duplicate the backpack in the battle menu');
assert.doesNotMatch(script, /button\.dataset\.menuAction === '材料'/, 'the removed material shortcut has no stale click handler');
assert.match(css, /grid-template-columns: repeat\(7, minmax\(0, 1fr\)\) !important;/, 'the seven remaining battle actions share the full row');
assert.match(css, /body:has\(\.battle-screen:not\(\.hidden\)\) \.toast[\s\S]*?bottom: calc\(92px/, 'battle loot notifications sit above the action bar');
assert.match(script, /<main class="drop-lookup-simple">/, 'drop lookup uses a simple item-list layout');
assert.doesNotMatch(script, /data-drop-map=|data-drop-travel=|drop-source-list/, 'drop lookup does not render map sources or travel actions');
assert.match(script, /<article class="drop-result-card">[\s\S]*?item\.name[\s\S]*?item\.typeLabel/, 'drop cards only show the item identity and type');

console.log('battlefield UI integration: assertions passed');
