const assert = require('node:assert/strict');
const policy = require('../blackstone-stronghold-policy.js');

assert.equal(policy.RULES.gameplayType, 'outpost-siege');
assert.equal(policy.RULES.objectiveCount, 5);
assert.equal(policy.RULES.outpostDamageReduction, null);
assert.equal(policy.RULES.outpostShield, null);
assert.deepEqual(policy.MONSTERS.map((monster) => monster.name), ['黑石守衛', '黑石弩手', '黑石狂戰士', '黑石戰犬', '黑石獅衛', '黑石蠻角勇士', '黑石督軍']);
assert.deepEqual(policy.MONSTERS.map((monster) => monster.rank), ['normal', 'normal', 'normal', 'normal', 'elite', 'elite', 'boss']);
assert.deepEqual(policy.MONSTERS.map((monster) => monster.race), ['human', 'goblin', 'orc', 'beast', 'lionkin', 'bullkin', 'orc']);
assert.deepEqual(policy.MONSTERS.map((monster) => monster.role), ['重甲前排', '遠程輸出', '雙斧近戰', '高速近戰', '高攻擊近戰', '高血量／重擊', '據點指揮官']);
assert.equal(policy.getMonstersByRank('normal').length, 4);
assert.equal(policy.getMonstersByRank('elite').length, 2);
assert.equal(policy.getMonstersByRank('boss').length, 1);
assert.equal(policy.getMonster('blackstone-warlord').name, '黑石督軍');
assert.equal(policy.getMonster('blackstone-guard').image, 'assets/blackstone-guard.png');
assert.equal(policy.getMonster('blackstone-crossbowman').image, 'assets/blackstone-crossbowman.png');
assert.equal(policy.getMonster('unknown'), null);
assert.ok(policy.MONSTERS.filter((monster) => !['blackstone-guard', 'blackstone-crossbowman'].includes(monster.id)).every((monster) => monster.image === null));
assert.ok(policy.MONSTERS.every((monster) => monster.stats === null
  && monster.dropTableId === null && monster.aiProfileId === null && monster.skillIds.length === 0 && monster.implemented === false));
const fs = require('node:fs');
const path = require('node:path');
const guard = fs.readFileSync(path.join(__dirname, '..', policy.getMonster('blackstone-guard').image));
assert.equal(guard.subarray(1, 4).toString(), 'PNG', 'the Blackstone guard is a PNG asset');
assert.equal(guard[25], 6, 'the Blackstone guard uses RGBA color with transparency');
const crossbowman = fs.readFileSync(path.join(__dirname, '..', policy.getMonster('blackstone-crossbowman').image));
assert.equal(crossbowman.subarray(1, 4).toString(), 'PNG', 'the Blackstone crossbowman is a PNG asset');
assert.equal(crossbowman[25], 6, 'the Blackstone crossbowman uses RGBA color with transparency');
assert.equal(policy.rollRequiredKills(() => 0), 10);
assert.equal(policy.rollRequiredKills(() => .999999), 70);
let state = policy.createState(() => 0);
for (let kill = 1; kill < 10; kill += 1) state = policy.recordMonsterKill(state);
assert.equal(state.outpostActive, false);
state = policy.recordMonsterKill(state);
assert.equal(state.outpostActive, true);
for (let outpost = 1; outpost <= 5; outpost += 1) {
  const result = policy.destroyOutpost(state, { now: 1000 * outpost, random: () => 0 });
  assert.equal(result.ok, true);
  assert.equal(result.state.enragedUntil, 1000 * outpost + 15000);
  assert.deepEqual(policy.getEnrage(result.state, 1000 * outpost), { active: true, attackBonus: .30, attackSpeedBonus: .30, remainingMs: 15000 });
  state = result.state;
  if (outpost < 5) for (let kill = 0; kill < 10; kill += 1) state = policy.recordMonsterKill(state);
}
assert.equal(state.destroyedOutposts, 5);
assert.equal(state.bossSpawned, true);
let guarantee = policy.createState(() => .999999);
for (let kill = 0; kill < 69; kill += 1) guarantee = policy.recordMonsterKill(guarantee);
assert.equal(guarantee.outpostActive, false);
guarantee = policy.recordMonsterKill(guarantee);
assert.equal(guarantee.outpostActive, true);
console.log('blackstone-stronghold-policy: assertions passed');
