const assert = require('node:assert/strict');
const policy = require('../blackstone-stronghold-policy.js');

assert.equal(policy.RULES.gameplayType, 'outpost-siege');
assert.equal(policy.RULES.objectiveCount, 5);
assert.equal(policy.RULES.outpostDamageReduction, null);
assert.equal(policy.RULES.outpostShield, null);
assert.deepEqual(policy.OUTPOSTS.map((outpost) => outpost.name), ['補給站', '兵營', '軍械庫', '哨塔', '指揮帳篷']);
assert.deepEqual(policy.OUTPOSTS.map((outpost) => outpost.effect.label), [
  '敵軍每秒恢復 1% 最大生命', '敵軍最大生命提高 20%', '敵軍攻擊提高 15%', '敵軍暴擊率提高 10%', '敵軍攻速提高 15%'
]);
assert.ok(policy.OUTPOSTS.every((outpost) => outpost.implemented && Object.isFrozen(outpost.effect)));
assert.equal(policy.getOutpostEffect('blackstone-armory').value, .15);
assert.equal(policy.getOutpost('unknown'), null);
assert.deepEqual(policy.MONSTERS.map((monster) => monster.name), ['黑石守衛', '黑石弩手', '黑石狂戰士', '黑石戰犬', '黑石獅衛', '黑石蠻角勇士', '黑石督軍']);
assert.deepEqual(policy.MONSTERS.map((monster) => monster.rank), ['normal', 'normal', 'normal', 'normal', 'elite', 'elite', 'boss']);
assert.deepEqual(policy.MONSTERS.map((monster) => monster.race), ['human', 'goblin', 'orc', 'beast', 'lionkin', 'bullkin', 'orc']);
assert.deepEqual(policy.MONSTERS.map((monster) => monster.role), ['重甲前排', '遠程輸出', '雙斧近戰', '高速近戰', '高攻擊近戰', '高血量／重擊', '據點指揮官']);
assert.equal(policy.getMonstersByRank('normal').length, 4);
assert.equal(policy.getMonstersByRank('elite').length, 2);
assert.equal(policy.getMonstersByRank('boss').length, 1);
assert.equal(policy.getMonster('blackstone-warlord').name, '黑石督軍');
assert.equal(policy.getMonster('blackstone-guard').image, 'assets/blackstone-guard.png');
assert.equal(policy.getMonster('blackstone-crossbowman').image, 'assets/blackstone-crossbowman.png');
assert.equal(policy.getMonster('blackstone-berserker').image, 'assets/blackstone-berserker.png');
assert.equal(policy.getMonster('blackstone-warhound').image, 'assets/blackstone-warhound.png');
assert.equal(policy.getMonster('blackstone-lion-guard').image, 'assets/blackstone-lion-guard.png');
assert.equal(policy.getMonster('blackstone-bullhorn-warrior').image, 'assets/blackstone-bullhorn-warrior.png');
assert.equal(policy.getMonster('blackstone-warlord').image, 'assets/blackstone-warlord.png');
assert.equal(policy.getMonster('unknown'), null);
assert.ok(policy.MONSTERS.every((monster) => monster.image !== null));
assert.ok(policy.MONSTERS.every((monster) => monster.level === 21 && monster.stats
  && monster.dropTableId === 'blackstone-stronghold-pending' && monster.aiProfileId
  && monster.skillIds.length > 0 && monster.implemented === true));
assert.deepEqual(policy.getMonster('blackstone-guard').stats, { maxHp: 520, attack: 54, defense: 48, evasion: 2, parry: 18, damageReduction: 14, attackSpeed: .78, xp: 55, gold: 28 });
assert.deepEqual(policy.getMonster('blackstone-crossbowman').stats, { maxHp: 340, attack: 66, defense: 25, evasion: 10, parry: 3, damageReduction: 3, attackSpeed: 1, xp: 54, gold: 29 });
assert.deepEqual(policy.getMonster('blackstone-berserker').stats, { maxHp: 440, attack: 62, defense: 28, evasion: 6, parry: 8, damageReduction: 5, attackSpeed: 1.15, xp: 58, gold: 31 });
assert.deepEqual(policy.getMonster('blackstone-warhound').stats, { maxHp: 380, attack: 55, defense: 24, evasion: 17, parry: 0, damageReduction: 4, attackSpeed: 1.4, xp: 56, gold: 27 });
assert.deepEqual(policy.getMonster('blackstone-lion-guard').stats, { maxHp: 1250, attack: 82, defense: 58, evasion: 8, parry: 14, damageReduction: 12, attackSpeed: .9, xp: 180, gold: 105 });
assert.deepEqual(policy.getMonster('blackstone-bullhorn-warrior').stats, { maxHp: 1550, attack: 78, defense: 64, evasion: 3, parry: 8, damageReduction: 16, attackSpeed: .75, xp: 195, gold: 115 });
assert.deepEqual(policy.getMonster('blackstone-warlord').stats, { maxHp: 6200, attack: 96, defense: 78, evasion: 4, parry: 16, damageReduction: 18, attackSpeed: .88, xp: 750, gold: 450 });
assert.deepEqual(policy.getCombatPool(), {
  normal: ['blackstoneStrongholdGuard', 'blackstoneStrongholdCrossbowman', 'blackstoneStrongholdBerserker', 'blackstoneStrongholdWarhound'],
  elite: ['blackstoneStrongholdLionGuard', 'blackstoneStrongholdBullhornWarrior'],
  boss: ['blackstoneStrongholdWarlord']
});
assert.equal(policy.getCombatMonster('blackstoneStrongholdWarlord').maxHp, 6200);
assert.equal(policy.getCombatMonster('blackstone-guard').defense, 48);
assert.equal(policy.rollLevel('blackstoneStrongholdWarhound'), 21);
assert.equal(policy.rollLevel('unknown'), null);
assert.equal(policy.resolveAction('blackstoneStrongholdGuard', .10), 'shield-bash');
assert.equal(policy.resolveAction('blackstoneStrongholdCrossbowman', .05), 'aimed-volley');
assert.equal(policy.resolveAction('blackstoneStrongholdCrossbowman', .20), 'armor-piercing-bolt');
assert.equal(policy.resolveAction('blackstoneStrongholdBerserker', .20), 'twin-axe-cleave');
assert.equal(policy.resolveAction('blackstoneStrongholdWarhound', .10), 'hunting-pounce');
assert.equal(policy.resolveAction('blackstoneStrongholdWarhound', .30), 'rending-bite');
assert.equal(policy.resolveAction('blackstoneStrongholdLionGuard', .10), 'lion-roar');
assert.equal(policy.resolveAction('blackstoneStrongholdLionGuard', .30), 'crushing-hammer');
assert.equal(policy.resolveAction('blackstoneStrongholdBullhornWarrior', .10), 'bullhorn-stampede');
assert.equal(policy.resolveAction('blackstoneStrongholdBullhornWarrior', .30), 'seismic-smash');
assert.equal(policy.getBossPhase('blackstoneStrongholdWarlord', 6200, 6200), 1);
assert.equal(policy.getBossPhase('blackstoneStrongholdWarlord', 4000, 6200), 2);
assert.equal(policy.getBossPhase('blackstoneStrongholdWarlord', 2000, 6200), 3);
assert.equal(policy.resolveAction('blackstoneStrongholdWarlord', .10, .25, 2000, 6200), 'warlord-execution');
assert.equal(policy.resolveAction('blackstoneStrongholdWarlord', .10, 1, 4000, 6200), 'warlord-command');
assert.equal(policy.resolveAction('blackstoneStrongholdWarlord', .30, 1, 6200, 6200), 'warhammer-sweep');
assert.deepEqual(policy.getCombatMultipliers('blackstoneStrongholdGuard', 200, 520), { attack: 1, attackSpeed: 1, defense: 1.25, evasion: 0 });
assert.deepEqual(policy.getCombatMultipliers('blackstoneStrongholdBerserker', 150, 440), { attack: 1.25, attackSpeed: 1.2, defense: .85, evasion: 0 });
assert.deepEqual(policy.getCombatMultipliers('blackstoneStrongholdWarlord', 2000, 6200), { attack: 1.25, attackSpeed: 1.15, defense: .9, evasion: 0 });
assert.equal(policy.getDamageMultiplier('seismic-smash'), 1.7);
assert.equal(policy.getDefenseIgnore('armor-piercing-bolt'), .35);
const fs = require('node:fs');
const path = require('node:path');
const guard = fs.readFileSync(path.join(__dirname, '..', policy.getMonster('blackstone-guard').image));
assert.equal(guard.subarray(1, 4).toString(), 'PNG', 'the Blackstone guard is a PNG asset');
assert.equal(guard[25], 6, 'the Blackstone guard uses RGBA color with transparency');
const crossbowman = fs.readFileSync(path.join(__dirname, '..', policy.getMonster('blackstone-crossbowman').image));
assert.equal(crossbowman.subarray(1, 4).toString(), 'PNG', 'the Blackstone crossbowman is a PNG asset');
assert.equal(crossbowman[25], 6, 'the Blackstone crossbowman uses RGBA color with transparency');
const berserker = fs.readFileSync(path.join(__dirname, '..', policy.getMonster('blackstone-berserker').image));
assert.equal(berserker.subarray(1, 4).toString(), 'PNG', 'the Blackstone berserker is a PNG asset');
assert.equal(berserker[25], 6, 'the Blackstone berserker uses RGBA color with transparency');
const warhound = fs.readFileSync(path.join(__dirname, '..', policy.getMonster('blackstone-warhound').image));
assert.equal(warhound.subarray(1, 4).toString(), 'PNG', 'the Blackstone warhound is a PNG asset');
assert.equal(warhound[25], 6, 'the Blackstone warhound uses RGBA color with transparency');
const lionGuard = fs.readFileSync(path.join(__dirname, '..', policy.getMonster('blackstone-lion-guard').image));
assert.equal(lionGuard.subarray(1, 4).toString(), 'PNG', 'the Blackstone lion guard is a PNG asset');
assert.equal(lionGuard[25], 6, 'the Blackstone lion guard uses RGBA color with transparency');
const bullhornWarrior = fs.readFileSync(path.join(__dirname, '..', policy.getMonster('blackstone-bullhorn-warrior').image));
assert.equal(bullhornWarrior.subarray(1, 4).toString(), 'PNG', 'the Blackstone bullhorn warrior is a PNG asset');
assert.equal(bullhornWarrior[25], 6, 'the Blackstone bullhorn warrior uses RGBA color with transparency');
const warlord = fs.readFileSync(path.join(__dirname, '..', policy.getMonster('blackstone-warlord').image));
assert.equal(warlord.subarray(1, 4).toString(), 'PNG', 'the Blackstone warlord is a PNG asset');
assert.equal(warlord[25], 6, 'the Blackstone warlord uses RGBA color with transparency');
const supplyStation = fs.readFileSync(path.join(__dirname, '..', policy.getOutpost('blackstone-supply-station').image));
assert.equal(supplyStation.subarray(1, 4).toString(), 'PNG', 'the Blackstone supply station is a PNG asset');
assert.equal(supplyStation[25], 6, 'the Blackstone supply station uses RGBA color with transparency');
const barracks = fs.readFileSync(path.join(__dirname, '..', policy.getOutpost('blackstone-barracks').image));
assert.equal(barracks.subarray(1, 4).toString(), 'PNG', 'the Blackstone barracks is a PNG asset');
assert.equal(barracks[25], 6, 'the Blackstone barracks uses RGBA color with transparency');
const armory = fs.readFileSync(path.join(__dirname, '..', policy.getOutpost('blackstone-armory').image));
assert.equal(armory.subarray(1, 4).toString(), 'PNG', 'the Blackstone armory is a PNG asset');
assert.equal(armory[25], 6, 'the Blackstone armory uses RGBA color with transparency');
const watchtower = fs.readFileSync(path.join(__dirname, '..', policy.getOutpost('blackstone-watchtower').image));
assert.equal(watchtower.subarray(1, 4).toString(), 'PNG', 'the Blackstone watchtower is a PNG asset');
assert.equal(watchtower[25], 6, 'the Blackstone watchtower uses RGBA color with transparency');
const commandTent = fs.readFileSync(path.join(__dirname, '..', policy.getOutpost('blackstone-command-tent').image));
assert.equal(commandTent.subarray(1, 4).toString(), 'PNG', 'the Blackstone command tent is a PNG asset');
assert.equal(commandTent[25], 6, 'the Blackstone command tent uses RGBA color with transparency');
assert.equal(policy.rollRequiredKills(() => 0), 10);
assert.equal(policy.rollRequiredKills(() => .999999), 70);
assert.equal(policy.rollOutpostId(undefined, () => 0), 'blackstone-supply-station');
assert.equal(policy.rollOutpostId(undefined, () => .999999), 'blackstone-command-tent');
assert.equal(policy.rollOutpostId(['unknown'], () => 0), null);
let state = policy.createState(() => 0);
assert.equal(state.availableOutpostIds.length, 5);
for (let kill = 1; kill < 10; kill += 1) state = policy.recordMonsterKill(state, () => 0);
assert.equal(state.outpostActive, false);
state = policy.recordMonsterKill(state, () => 0);
assert.equal(state.outpostActive, true);
assert.equal(state.activeOutpostId, 'blackstone-supply-station');
const destroyedIds = [];
for (let outpost = 1; outpost <= 5; outpost += 1) {
  const result = policy.destroyOutpost(state, { now: 1000 * outpost, random: () => 0 });
  assert.equal(result.ok, true);
  destroyedIds.push(result.destroyedOutpostId);
  assert.ok(result.effectRemoved);
  assert.equal(result.state.enragedUntil, 1000 * outpost + 15000);
  assert.deepEqual(policy.getEnrage(result.state, 1000 * outpost), { active: true, attackBonus: .30, attackSpeedBonus: .30, remainingMs: 15000 });
  state = result.state;
  if (outpost < 5) {
    for (let kill = 0; kill < 10; kill += 1) state = policy.recordMonsterKill(state, () => 0);
    assert.ok(state.activeOutpostId);
  }
}
assert.equal(state.destroyedOutposts, 5);
assert.equal(state.bossSpawned, true);
assert.deepEqual(destroyedIds, policy.OUTPOSTS.map((outpost) => outpost.id));
assert.equal(new Set(destroyedIds).size, 5);
assert.deepEqual(state.availableOutpostIds, []);
let guarantee = policy.createState(() => .999999);
for (let kill = 0; kill < 69; kill += 1) guarantee = policy.recordMonsterKill(guarantee);
assert.equal(guarantee.outpostActive, false);
guarantee = policy.recordMonsterKill(guarantee);
assert.equal(guarantee.outpostActive, true);
console.log('blackstone-stronghold-policy: assertions passed');
