// Unit checks only; do not add combat runs beyond the requested 600.
const assert = require('node:assert/strict');
const rules = require('./simulations/chapter-three-34-rules.js');
const living = t => ({ ...t, maxHp: t.hp, currentHp: t.hp, attackAt: 10 });
const guard = living(rules.normals[2]);
assert.equal(guard.dr, 22);
assert.equal(rules.effectiveDr(guard), 27);
guard.currentHp = guard.maxHp / 2;
assert.equal(rules.effectiveDr(guard), 22);
guard.currentHp--;
assert.equal(rules.effectiveDr(guard), 22);
assert.equal(guard.dr, 22, 'base DR was not changed');
const wolf = living(rules.normals[3]);
assert.deepEqual([wolf.evasion, wolf.parry, rules.effectiveDr(wolf)], [8, 5, 10]);
rules.onSkillHit(wolf, 5);
assert.equal(rules.speedMultiplier(wolf, 5), 1.1);
assert.equal(wolf.charge34Until, 9);
const pending = wolf.attackAt;
rules.onSkillHit(wolf, 6);
assert.equal(wolf.attackAt, pending, 'refresh is not another speed stack');
assert.equal(wolf.charge34Until, 10);
assert.equal(rules.speedMultiplier(wolf, 10), 1);
const champion = living(rules.elite);
champion.currentHp = champion.maxHp / 2;
rules.afterDamage(champion, 4);
assert.equal(champion.fervor34Triggered, undefined);
champion.currentHp--;
rules.afterDamage(champion, 5);
rules.afterDamage(champion, 6);
assert.equal(champion.fervor34Count, 1);
assert.equal(rules.attackMultiplier(champion), 1.08);
assert.equal(rules.speedMultiplier(champion, 6), 1.08);
const boss = living(rules.boss), summons = [];
boss.spawnSummon = (t, now) => summons.push({ ...living(t), spawnedAt: now });
boss.dismissSummons = () => summons.forEach(e => { e.currentHp = 0; });
boss.currentHp = 14000;
rules.afterDamage(boss, 20);
rules.afterDamage(boss, 21);
assert.equal(summons.length, 1);
boss.currentHp = 8000;
rules.afterDamage(boss, 40);
assert.equal(summons.length, 2);
boss.currentHp = 5000;
rules.afterDamage(boss, 60);
rules.afterDamage(boss, 61);
assert.equal(boss.rage34Count, 1);
assert.equal(summons.length, 2);
assert.equal(boss.summon70.count, 1);
assert.equal(boss.summon40.count, 1);
assert.equal(rules.attackMultiplier(boss), 1.1);
assert.equal(rules.speedMultiplier(boss, 61), 1.1);
assert.equal(rules.defenseMultiplier(boss), .9);
const player = { hp: 100, maxHp: 1000, killHeal: .02 };
for (const summon of summons) assert.equal(rules.killHealAmount(player, summon), 0);
assert.equal(rules.killHealAmount(player, boss), 20);
boss.currentHp = 0;
rules.afterDamage(boss, 70);
assert.ok(summons.every(e => e.currentHp === 0));
assert.equal(summons.length, 2);
console.log('Chapter 3-4 rule checks passed; no extra simulations');
const result = require('./simulations/results/chapter-three-34-complete-v1.json');
assert.deepEqual(result.templates, { normals: rules.normals, elite: rules.elite, boss: rules.boss });
assert.equal(result.totalRuns, 600);
assert.equal(result.cells.reduce((n, cell) => n + cell.runs, 0), 600);
assert.equal(result.eliteChance, .05);
for (const party of ['A', 'B']) assert.deepEqual(result.cells.filter(c => c.party === party).map(c => [c.mode, c.stage]), [['loop', '10/25'], ['loop', '15/25'], ['boss', '15/25']]);
for (const cell of result.cells) {
  assert.equal(cell.runs, 100);
  if (cell.mode === 'loop') {
    assert.ok(Math.abs(Object.values(cell.enemyDamageShares).reduce((a, b) => a + b, 0) - 1) < 1e-10);
    assert.ok(cell.fullPartySurvivalRate <= cell.survivalRate);
    assert.ok(cell.fervorTriggerRate >= 0 && cell.fervorTriggerRate <= 1);
    assert.ok(cell.warDrumCoverage >= 0 && cell.warDrumCoverage <= 1);
  } else {
    assert.equal(cell.killRate + cell.wipeRate + cell.timeoutRate, 1);
    assert.equal(cell.maxEnemies, 3);
    assert.equal(cell.summon70.triggerRate, 1);
    assert.equal(cell.summon40.triggerRate, 1);
    assert.equal(cell.summon70.maxTriggers, 1);
    assert.equal(cell.summon40.maxTriggers, 1);
    assert.ok(cell.summon70.damagePerRun > 0 && cell.summon40.damagePerRun > 0);
    assert.ok(Math.abs(cell.summon70.damagePerRun + cell.summon40.damagePerRun - cell.summonDamagePerRun) < 1e-8);
    assert.equal(cell.rageEntryRate, 1);
    assert.equal(cell.maxRageTriggers, 1);
    assert.ok(Math.abs(cell.rageStats.attack - 198) < 1e-8);
    assert.ok(Math.abs(cell.rageStats.speed - .902) < 1e-8);
    assert.ok(Math.abs(cell.rageStats.defense - 133.2) < 1e-8);
    assert.equal(cell.summonKillHealingTotal, 0);
    assert.equal(cell.liveSummonsAfterBossDeath, 0);
    assert.ok(Math.abs(cell.rageEntrySeconds + cell.rageDurationSeconds - cell.averageKillSeconds) < 1e-8);
  }
}
console.log('Recorded 600-run result checks passed');
