const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const script = fs.readFileSync(path.join(root, 'script.js'), 'utf8');
const index = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const rendererStart = script.indexOf('function renderBlackForestRegions()');
const rendererEnd = script.indexOf('function selectAllCommonEquipment', rendererStart);
const blackForestRenderer = rendererStart >= 0 && rendererEnd > rendererStart ? script.slice(rendererStart, rendererEnd) : '';

assert.match(index, /chapter-two-map-policy\.js[\s\S]*script\.js/, 'chapter-two data loads before the game');
assert.match(index, /black-forest-corruption-policy\.js[\s\S]*blackstone-stronghold-policy\.js[\s\S]*black-forest-depths-policy\.js[\s\S]*chapter-two-map-policy\.js/);
assert.match(index, /black-forest-entrance-policy\.js[\s\S]*chapter-two-map-policy\.js/);
assert.match(index, /black-forest-trail-policy\.js[\s\S]*chapter-two-map-policy\.js/);
assert.match(index, /spider-nest-policy\.js[\s\S]*chapter-two-map-policy\.js/);
assert.match(index, /forest-altar-policy\.js[\s\S]*chapter-two-map-policy\.js/);
assert.match(index, /VER\. 0\.4\.99/);
assert.match(index, /black-forest-depths-policy\.js\?v=20260810-depths-boss-v13/);
assert.match(index, /blackstone-stronghold-policy\.js\?v=20260810-outpost-objective-v17/);
assert.match(index, /black-forest-trail-policy\.js\?v=20260809-trail-balance-v10/);
assert.match(index, /spider-nest-policy\.js\?v=20260809-spider-combat-v9/);
assert.match(index, /forest-altar-policy\.js\?v=20260810-altar-skills-v12/);
assert.match(index, /chapter-two-map-policy\.js\?v=20260810-depths-boss-v20/);
assert.match(index, /world\/dfcffd3b95e6ceed746c3a05b26dae74a9331925\/script\.js/);
assert.match(index, /VER\. \d+\.\d+\.\d+/, 'the game exposes a semantic version');
assert.match(script, /\.\.\.ChapterTwoMapPolicy\.MAPS/, 'chapter-two maps join the shared progression data');
assert.match(script, /blackForestEntrance: BlackForestEntrancePolicy\.getCombatPool\(\)/);
assert.match(script, /blackForestTrail: BlackForestTrailPolicy\.getCombatPool\(\)/);
assert.match(script, /BlackForestEntrancePolicy\.resolveAction/);
assert.match(script, /BlackForestTrailPolicy\.resolveAction/);
assert.match(script, /spiderNest: SpiderNestPolicy\.getCombatPool\(\)/);
assert.match(script, /SpiderNestPolicy\.resolveAction/);
assert.match(script, /blackstoneStronghold: BlackstoneStrongholdPolicy\.getCombatPool\(\)/);
assert.match(script, /mapId === 'blackstone-stronghold'\) return mapMonsterPools\.blackstoneStronghold/);
assert.match(script, /BlackstoneStrongholdPolicy\.getCombatMonster/);
assert.match(script, /forestAltar: ForestAltarPolicy\.getCombatPool\(\)/);
assert.match(script, /mapId === 'forest-altar'\) return mapMonsterPools\.forestAltar/);
assert.match(script, /ForestAltarPolicy\.getCombatMonster/);
assert.match(script, /ForestAltarPolicy\.resolveAction/);
assert.match(script, /ForestAltarPolicy\.getDamageMultiplier/);
assert.match(script, /ForestAltarPolicy\.getCombatMultipliers/);
assert.match(script, /ForestAltarPolicy\.getControlEffect/);
assert.match(script, /blackForestDepths: BlackForestDepthsPolicy\.getCombatPool\(\)/);
assert.match(script, /mapId === 'black-forest-depths'\) return mapMonsterPools\.blackForestDepths/);
assert.match(script, /BlackForestDepthsPolicy\.getCombatMonster/);
assert.match(script, /BlackForestDepthsPolicy\.resolveAction/);
assert.match(script, /BlackForestDepthsPolicy\.getDamageMultiplier/);
assert.match(script, /BlackForestDepthsPolicy\.getCombatMultipliers/);
assert.match(script, /healBlackForestDepthsAlly/);
assert.match(script, /inflictBlackForestDepthsCorruption/);
assert.match(script, /BlackForestDepthsPolicy\.getBossPhase/);
assert.match(script, /summonBlackForestDepthsRoot/);
assert.match(script, /forestSpiritAlive/);
assert.match(script, /enemyDepthsPhase/);
assert.match(script, /BlackstoneStrongholdPolicy\.applyOutpostEffect/);
assert.match(script, /BlackstoneStrongholdPolicy\.resolveAction/);
assert.match(script, /BlackstoneStrongholdPolicy\.getDamageMultiplier/);
assert.match(script, /BlackstoneStrongholdPolicy\.getDefenseIgnore/);
assert.match(script, /BlackstoneStrongholdPolicy\.getCombatMultipliers/);
assert.match(script, /strongholdAction === 'rending-bite'/);
assert.match(script, /strongholdAction === 'shield-bash'/);
assert.match(script, /strongholdAction === 'bullhorn-stampede'/);
assert.match(script, /enemy\.healthRegenPerSecond/);
assert.match(script, /BlackstoneStrongholdPolicy\.recordMonsterKill\(battle\.blackstoneStrongholdState\)/);
assert.match(script, /function processStrongholdOutpost\(/);
assert.match(script, /BlackstoneStrongholdPolicy\.damageOutpost/);
assert.match(script, /function spawnStrongholdWarlord\(/);
assert.match(script, /function renderStrongholdObjective\(/);
assert.match(script, /strongholdCommandUntil/);
assert.match(script, /strongholdEnrageMultiplier/);
assert.match(script, /inflictSpiderNestPoison/);
assert.match(script, /summonSpiderNestMonster/);
assert.match(script, /enemySpiderNestPhase/);
assert.match(script, /inflictBlackForestDot/);
assert.match(script, /inflictBlackForestTrailPoison/);
assert.match(script, /summonBlackstonePoisonSpider/);
assert.match(script, /blackstoneMarkedUntil/);
assert.match(script, /blackstoneArmorBreakUntil/);
assert.match(script, /enemyCaptainShieldUntil/);
assert.match(script, /blackForestCorruption: BlackForestCorruptionPolicy\.normalizeState\(saved\.blackForestCorruption\)/);
assert.match(script, /if \(map\.chapter === 2\) BlackForestCorruptionPolicy\.enterChapter\(progress\)/);
assert.match(script, /BlackForestCorruptionPolicy\.applyCombatStats\(stats, progress\.blackForestCorruption, activeMap\.chapter === 2\)/);
assert.match(script, /BlackForestDepthsPolicy\.applyDenseFogAccuracy\(corruptedStats\.accuracy, activeMap\.id\)/);
assert.match(script, /function processBlackForestCorruption\(now = Date\.now\(\)\)[\s\S]*BlackForestCorruptionPolicy\.getHpLoss/);
assert.match(script, /processBlackForestCorruption\(now\)/);
assert.match(script, /previousMapId: 'plains-depths'/, 'chapter two connects from the first chapter finale');
assert.match(script, /function renderBlackForestRegions\(/, 'black forest has a chapter region view');
assert.match(blackForestRenderer, /ChapterTwoMapPolicy\.getDungeon\(region\.id\)/, 'the stronghold preview reads the dungeon foundation');
assert.match(blackForestRenderer, /<em>規劃中<\/em>/, 'unfinished maps are visibly marked as planned');
assert.doesNotMatch(blackForestRenderer, /data-select-map=/, 'planned chapter-two cards do not expose entry controls');
assert.match(script, /if \(regionHubButton\.dataset\.openMapRegion === 'black-forest'\) renderBlackForestRegions\(\)/,
  'the shared region action opens the second chapter view');

console.log('chapter-two-map-integration: assertions passed');
