// Pure rule checks: no additional combat configurations or random runs.
const assert = require('node:assert/strict');
const r = require('./simulations/chapter-three-35-rules.js');
const living = t => ({ ...t, currentHp: t.hp, maxHp: t.hp, attackAt: 20 });
const priest = living(r.normals[0]), other = living(r.normals[1]);
r.sacrifice(priest, [priest, other], 12);
assert.equal(priest.currentHp, 993.6);
assert.equal(r.extraDr(priest, 13), 0);
assert.equal(r.extraDr(other, 13), 6);
r.sacrifice(priest, [priest, other], 14);
assert.equal(r.extraDr(other, 18), 6);
assert.equal(r.extraDr(other, 19), 0);
priest.currentHp = .5;
r.sacrifice(priest, [priest, other], 20);
assert.equal(priest.currentHp, .5, 'self loss neither kills nor heals at sub-1 HP');
const fanatic = living(r.normals[1]);
fanatic.currentHp = fanatic.maxHp * .3;
r.afterDamage(fanatic, 0);
assert.equal(fanatic.fanaticTriggered35, undefined);
fanatic.currentHp--;
r.afterDamage(fanatic, 1);
r.afterDamage(fanatic, 2);
assert.equal(fanatic.fanaticCount35, 1);
assert.equal(r.attackMultiplier(fanatic, 100), 1.12);
assert.equal(r.speedMultiplier(fanatic, 100), 1.12);
assert.equal(r.defenseMultiplier(fanatic), .9);
const stone = living(r.normals[2]);
for (let i = 0; i < 5; i++) assert.equal(r.shellMultiplier(stone, 10), 1);
assert.equal(r.shellMultiplier(stone, 0), 1);
assert.equal(stone.shellHits35, 5);
assert.equal(r.shellMultiplier(stone, 10), .7);
assert.equal(stone.shellHits35, 0);
assert.equal(r.shellMultiplier(stone, 10), 1);
const player = { attack: 100, defense: 100, speed: 1 }, ally = { attack: 100 };
r.onSkillHit(r.normals[3], player, 10);
assert.equal(r.playerDamageMultiplier(player, 13), .94);
assert.equal(r.playerDamageMultiplier(ally, 13), 1);
r.onSkillHit(r.normals[3], player, 12);
assert.equal(r.playerDamageMultiplier(player, 15), .94);
assert.equal(r.playerDamageMultiplier(player, 16), 1);
assert.deepEqual([player.attack, player.defense, player.speed], [100, 100, 1]);
const elite = living(r.elite);
elite.currentHp = 2149;
r.afterDamage(elite, 1);
assert.equal(r.attackMultiplier(elite, 8), 1.08);
assert.equal(r.extraDr(elite, 8), 5);
assert.equal(r.attackMultiplier(elite, 9), 1);
assert.equal(r.extraDr(elite, 9), 0);
r.afterDamage(elite, 12);
assert.equal(elite.awakeningCount35, 1);
assert.equal(elite.awakeningUntil35, 9);
const boss = living(r.boss);
boss.onForbidden35 = active => { player.forbidden35 = active; ally.forbidden35 = active; };
boss.currentHp = 15750;
r.afterDamage(boss, 1);
assert.equal(boss.currentHp, 14962.5);
assert.equal(r.attackMultiplier(boss, 2), 1.08);
assert.equal(r.speedMultiplier(boss, 2), 1);
boss.currentHp = 9000;
r.afterDamage(boss, 5);
assert.equal(boss.currentHp, 8550);
assert.equal(r.attackMultiplier(boss, 6), 1.08, 'stage II replaces stage I, not +16%');
assert.equal(r.speedMultiplier(boss, 6), 1.08);
assert.equal(r.attackMultiplier(boss, 15), 1);
assert.equal(r.speedMultiplier(boss, 15), 1);
boss.currentHp = 4499;
r.afterDamage(boss, 18);
r.afterDamage(boss, 19);
assert.equal(boss.forbiddenCount35, 1);
assert.equal(boss.ritual135.count, 1);
assert.equal(boss.ritual235.count, 1);
assert.equal(r.defenseMultiplier(boss), .85);
assert.equal(r.playerDamageMultiplier(ally, 19), .92);
r.onSkillHit(boss, player, 19);
assert.equal(r.playerDamageMultiplier(player, 20), .92 * .92);
assert.equal(r.playerDamageMultiplier(player, 24), .92);
boss.currentHp = 0;
r.afterDamage(boss, 25);
assert.equal(r.playerDamageMultiplier(ally, 25), 1);
console.log('Chapter 3-5 mechanics checks passed; no extra simulations');
const result = require('./simulations/results/chapter-three-35-complete-v1.json');
assert.deepEqual(result.templates, { normals: r.normals, elite: r.elite, boss: r.boss });
assert.equal(result.totalValidRuns, 600);
assert.equal(result.cells.reduce((n, cell) => n + cell.runs, 0), 600);
assert.equal(result.eliteChance, .05);
for (const party of ['A', 'B']) assert.deepEqual(result.cells.filter(c => c.party === party).map(c => [c.mode, c.stage]), [['loop', '12/30'], ['loop', '18/30'], ['boss', '18/30']]);
for (const cell of result.cells) {
  assert.equal(cell.runs, 100);
  if (cell.mode === 'loop') {
    assert.ok(Math.abs(Object.values(cell.enemyDamageShares).reduce((a, b) => a + b, 0) - 1) < 1e-10);
    assert.ok(cell.fullPartySurvivalRate <= cell.survivalRate);
    for (const key of ['bloodDrCoverage', 'runeDebuffCoverage', 'awakeningTriggerRate', 'fanaticTriggerRate']) assert.ok(cell[key] >= 0 && cell[key] <= 1);
  } else {
    assert.equal(cell.killRate + cell.wipeRate + cell.timeoutRate, 1);
    assert.equal(cell.maxEnemies, 1);
    for (const ritual of [cell.ritual70, cell.ritual40]) {
      assert.equal(ritual.triggerRate, 1);
      assert.equal(ritual.maxTriggers, 1);
      assert.equal(ritual.buffObservedSeconds, 10);
    }
    assert.equal(cell.forbiddenEntryRate, 1);
    assert.equal(cell.maxForbiddenTriggers, 1);
    assert.ok(cell.longestRunSeconds <= 120);
    assert.ok(Math.abs(cell.ritual70.selfDamagePerRun + cell.ritual40.selfDamagePerRun - cell.bossSelfDamagePerRun) < 1e-8);
    assert.ok(Math.abs(cell.forbiddenEntrySeconds + cell.forbiddenDurationSeconds - cell.averageKillSeconds) < 1e-8);
  }
}
console.log('Chapter 3-5 valid 600-run result checks passed');
