const assert = require('assert');
const fs = require('fs');
const path = require('path');

const source = fs.readFileSync(path.join(__dirname, '..', 'script.js'), 'utf8');
const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
const gameCss = fs.readFileSync(path.join(__dirname, '..', 'styles', 'game.css'), 'utf8');
const appCss = fs.readFileSync(path.join(__dirname, '..', 'style.css'), 'utf8');

assert.match(html, /equipment-affix-policy\.js/, 'affix policy loads before the main game script');
assert.match(html, /href="style\.css\?v=20260822-inventory-image-containment-v1"/, 'the affix UI stylesheet loads from the same deployed revision');
assert.match(html, /equipment-affix-policy\.js\?v=20260903-special-epic-v1/, 'the affix formatter uses the current local build');
assert.match(html, /armor-penetration-policy\.js\?v=20260903-armor-penetration-v1/, 'armor penetration policy loads before the main game script');
assert.match(html, /conditional-damage-policy\.js\?v=20260903-conditional-damage-v1/, 'conditional damage policy loads before the main game script');
assert.match(html, /critical-resource-recovery-policy\.js\?v=20260903-critical-resource-recovery-v1/, 'critical resource recovery policy loads before the main game script');
assert.match(html, /direct-hit-health-recovery-policy\.js\?v=20260903-direct-hit-health-recovery-v1/, 'direct-hit health recovery policy loads before the main game script');
assert.match(html, /chapter-three-crafted-epic-ability-policy\.js\?v=20260903-chapter3-crafted-epic-v1/, 'crafted epic ability policy loads before the main game script');
assert.match(html, /control-effect-policy\.js\?v=20260903-control-resistance-v1/, 'the shared player control policy loads before the main game script');
assert.match(html, /script\.js\?v=20260903-special-epic-v1/, 'the affix UI renderer uses the current local build');
assert.match(source, /equipmentAffixMigrationVersion !== 'green-affix-v1'/, 'legacy saves receive the affix compatibility migration');
assert.match(source, /EquipmentAffixPolicy\.normalizeEquipment\(item\)/, 'inventory and equipped items are normalized on load');
assert.match(source, /EquipmentAffixPolicy\.getEquippedAffixStats\(progress\.equipment\)/, 'stats read only the equipped item collection');
assert.match(source, /equipment\.maxHpPercent/, 'maximum-health affixes feed the character calculation');
assert.match(source, /equipment\.defensePercent/, 'defense affixes feed the character calculation');
assert.match(source, /equipment\.criticalChance/, 'critical chance affixes feed the character calculation');
assert.match(source, /equipment\.attackSpeedPercent/, 'attack-speed affixes feed the character calculation');
assert.match(source, /armorPenetrationPercent: \(affixes\.armorPenetrationPercent \|\| 0\) \/ 100/, 'armor penetration enters the shared equipment aggregation');
assert.match(source, /ArmorPenetrationPolicy\.getTotalArmorIgnore\([\s\S]*skillArmorIgnore: options\.armorIgnore[\s\S]*equipmentArmorPenetration: attackerStats\.armorPenetrationPercent[\s\S]*attackKind: options\.attackKind/, 'online attacks combine skill and eligible equipment armor ignore at one defense entry point');
assert.match(source, /enemy\.defense \* \(1 - armorIgnore\)/, 'the combined ratio reduces enemy defense');
assert.match(source, /lowHealthDamagePercent: \(affixes\.lowHealthDamagePercent \|\| 0\) \/ 100[\s\S]*highHealthDamagePercent: \(affixes\.highHealthDamagePercent \|\| 0\) \/ 100/, 'conditional damage affixes enter shared equipment aggregation');
assert.match(source, /criticalResourceRecoveryPercent: \(affixes\.criticalResourceRecoveryPercent \|\| 0\) \/ 100/, 'critical recovery enters shared equipment aggregation');
assert.match(source, /directHitHealthRecoveryPercent: \(affixes\.directHitHealthRecoveryPercent \|\| 0\) \/ 100/, 'direct-hit recovery amount enters shared equipment aggregation');
assert.match(source, /controlResistancePercent: \(affixes\.controlResistancePercent \|\| 0\) \/ 100/, 'control resistance enters shared equipment aggregation');
assert.equal((source.match(/applyControlEffectToPlayer\(target, \{ type: 'stun'/g) || []).length, 7, 'all seven active player stun sources use the shared entry point');
assert.doesNotMatch(source.slice(source.indexOf('function enemyAttackTick()')), /target\.stunnedUntil\s*=/, 'the formal enemy attack path no longer writes stun state directly');
assert.match(source, /function applyBlackstoneAttackSpeedPenalty[\s\S]*applyControlEffectToPlayer\(member, \{ type: 'attack-speed-slow'/, 'all existing attack-speed slow callers retain their wrapper and enter the shared policy');
assert.match(source, /blackForestAction === 'binding-arrow'\) logBattle/, 'binding arrow remains display and damage only');
assert.match(source, /blackForestAction === 'root-strike'\) logBattle/, 'root strike remains display and damage only');
assert.match(source, /function resolveEnemyDirectHitRecovery\(member, actualDamage, stats = member\?\.stats, random = Math\.random, options = \{\}\)[\s\S]*damageKind: 'enemy-direct'[\s\S]*recoveryPercent: stats\?\.directHitHealthRecoveryPercent/, 'all eligible enemy damage calls one post-damage recovery entry point');
assert.match(source, /target\.currentHp = Math\.max\(0, target\.currentHp - damage\);\s*resolveEnemyDirectHitRecovery\(target, damage, stats\);/, 'party enemy attacks resolve recovery after actual health damage');
assert.match(source, /attacker\.currentHp = Math\.max\(0, attacker\.currentHp - actualCounterDamage\);\s*resolveEnemyDirectHitRecovery\(attacker, actualCounterDamage, counterStats, Math\.random, \{ triggerWasteland: false \}\);/g, 'enemy parry counters retain recovery handling but do not stack wasteland resilience from reflected damage');
assert.match(source, /member\.resourceCurrent = member\.resourceType === 'arrows'[\s\S]*CriticalResourceRecoveryPolicy\.resolveExecution\(member, \{[\s\S]*attackKind: skill\.id === 'companion' \? 'companion' : 'skill'[\s\S]*hadDirectHit: hits\.length > 0/, 'one skill execution resolves critical recovery once after paying its resource cost and excludes companion damage');
assert.match(source, /if \(member\.resourceType === 'rage'\)[^\n]+[\s\S]*CriticalResourceRecoveryPolicy\.resolveExecution\(member, \{ attackKind: 'basic', critical, hadDirectHit: true/, 'a successful basic attack resolves critical recovery once');
assert.match(source, /ConditionalDamagePolicy\.getDamageMultiplier\([\s\S]*currentHp: attacker\?\.currentHp[\s\S]*attackKind: options\.attackKind/, 'basic and counter damage read current HP at the common damage entry point');
assert.match(source, /const conditionalDamageMultiplier = ConditionalDamagePolicy\.getDamageMultiplier\(\{ currentHp: member\.currentHp[\s\S]*attackKind: 'skill'[\s\S]*targets\.map[\s\S]*conditionalDamageMultiplier,/, 'multi-target skills snapshot one conditional multiplier before resolving targets');
['skillDamagePercent', 'eliteDamagePercent', 'bossDamagePercent', 'basicAttackDamagePercent', 'killHealthRecoveryPercent', 'killResourceRecoveryPercent', 'poisonResistancePercent'].forEach((stat) => {
  assert.match(source, new RegExp(`${stat}: Math`), `chapter-two combat stat ${stat} feeds the character calculation`);
});
assert.match(source, /criticalDamageMultiplier: 1\.5 \+ Math\.max\(0, equipment\.criticalDamagePercent \+ passiveTotal/, 'equipment and passive critical damage increase the player critical multiplier');
assert.match(source, /updatePartyMemberHealthRegeneration\(member, now\)/, 'battle ticks apply equipped health regeneration');
assert.match(source, /skill\.id === 'fireball'\) hits\.forEach[\s\S]*applyDot\(target\.index, 'burn'/, 'fireball inherently applies burn on hit');
assert.doesNotMatch(source, /hasEquippedSpecialAbility\(member\.equipment, 'mage_fireball_burn'\)/, 'fireball burn does not depend on equipment');
assert.match(source, /EquipmentAffixPolicy\.formatAffix\(entry\)/, 'inventory, comparison and worn views share the affix text renderer');
assert.match(source, /chapterTwoCraftedBaseStatsMigrationVersion !== 'chapter2-crafted-base-stats-v1'/, 'existing chapter-two crafted instances receive their template base stats once');
assert.match(source, /chapterThreeBlueCraftedBaseStatsMigrationVersion !== 'chapter3-blue-crafted-base-stats-v1'/, 'existing chapter-three blue crafted instances receive finalized template base stats once');
assert.match(source, /chapterThreeEpicCraftedTemplateMigrationVersion !== 'chapter3-epic-crafted-template-v1'/, 'existing chapter-three epic crafted instances receive the finalized template once');
assert.match(source, /chapterThreeSpecialEquipmentTemplateMigrationVersion !== 'chapter3-special-equipment-template-v1'/, 'existing chapter-three monster epic instances receive the finalized template once');
assert.match(source, /specialBasicExecution\.guaranteedCritical \|\|[\s\S]*CriticalResourceRecoveryPolicy\.resolveExecution\(member, \{ attackKind: 'basic', critical, hadDirectHit: true/, 'runemark afterimage enters the formal critical path and its result reaches critical recovery');
assert.match(source, /resourceBeforeSkillCost = member\.resourceCurrent[\s\S]*actualResourceSpent = Math\.max\(0, resourceBeforeSkillCost - member\.resourceCurrent\)[\s\S]*resolveManaSurge\(member, actualResourceSpent/, 'mana surge reads the actual resource delta once per successful skill execution');
assert.match(source, /const craftedEpicExecution = ChapterThreeCraftedEpicAbilityPolicy\.beginSkillExecution\(member, now, \{ eligible: skill\.id !== 'companion' \}\)[\s\S]*targets\.map[\s\S]*craftedEpicExecution/, 'a multi-target skill shares one crafted epic execution snapshot and companion skills are excluded');
assert.match(source, /ChapterThreeCraftedEpicAbilityPolicy\.completeSkillExecution\(member, craftedEpicExecution, now\)/, 'only a validated successful active-skill execution advances crafted epic states');
assert.match(source, /ChapterThreeCraftedEpicAbilityPolicy\.getWastelandDamageReduction\(target, now\)[\s\S]*target\.currentHp = Math\.max\(0, target\.currentHp - damage\);[\s\S]*resolveEnemyDirectHitRecovery\(target, damage, stats\)/, 'wasteland resilience reduces the next hit before that direct hit adds or refreshes a stack');
assert.match(source, /CraftingPolicy\.applyCraftedBaseStats\(item\)/, 'inventory and equipped legacy items use the same compatibility path');
assert.match(source, /function equipmentDetailsHtml\(item\)/, 'equipment inventory rows use a dedicated details renderer');
assert.match(source, /equipment-affix-title">裝備詞綴/, 'the affix section has a clear title');
assert.match(source, /source === '固定'/, 'affixes expose fixed and random source labels');
assert.match(source, /equipment-affix-value/, 'affix values have a dedicated emphasis element');
assert.match(appCss, /\.equipment-affix-section\{[^}]*border-top:/, 'base stats and affixes are separated visually');
assert.match(appCss, /\.equipment-affix-line\{[^}]*grid-template-columns:/, 'each affix renders on its own aligned line');
assert.match(appCss, /\.equipment-affix-value\{[^}]*font-weight:900/, 'affix values use strong emphasis');
assert.match(source, /affixes: item\.affixes \|\| \[\]/, 'stacking distinguishes equipment with different affixes');
assert.doesNotMatch(source, /equipmentScore|equipmentValue|評分/, 'inventory and comparison no longer expose equipment scores');
assert.doesNotMatch(gameCss, /equipment-score|score-difference/, 'removed score UI has no stale styles');
assert.doesNotMatch(source, /class="item-quality"/, 'inventory, comparison and equipped slots identify quality by frame color instead of text');
assert.match(gameCss, /\.inventory-item\.quality-excellent,.equipment-frame\.quality-excellent\{border-color:#35d778!important/, 'green equipment uses a strong green inventory and equipment frame');
assert.match(html, /inventory-sale-policy\.js[\s\S]*script\.js/, 'sale policy loads before inventory integration');
assert.match(html, /id="sell-confirm-modal"/, 'batch selling has a dedicated confirmation dialog');
assert.match(source, /data-select-common-equipment>勾選全部白色裝備/, 'inventory exposes one-click common equipment selection');
assert.match(source, /InventorySalePolicy\.isCommonEquipment\(item\)/, 'common equipment selection uses the shared quality policy');
assert.doesNotMatch(source, /data-select-unusable-junk|selectUnusableJunkEquipment/, 'obsolete unusable junk quick selection is removed');
assert.match(source, /InventorySalePolicy\.summarizeSelection/, 'selection count and expected gold are recalculated during render');
assert.match(source, /InventorySalePolicy\.sellSelection/, 'confirmed sales use the shared atomic sale policy');
assert.doesNotMatch(source, /data-toggle-junk-ids|data-scrap-ids|toggleEquipmentJunkMark/, 'equipment rows no longer show per-item sale or junk-mark controls');
assert.doesNotMatch(source, /enhanceEquipment|enhancementRules|data-enhance-slot|enhancementBonus/, 'equipment enhancement rules and UI are fully removed');

console.log('equipment-affix-integration: assertions passed');
