const assert = require('assert');
const fs = require('fs');
const path = require('path');

const source = fs.readFileSync(path.join(__dirname, '..', 'script.js'), 'utf8');
const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
const gameCss = fs.readFileSync(path.join(__dirname, '..', 'styles', 'game.css'), 'utf8');
const appCss = fs.readFileSync(path.join(__dirname, '..', 'style.css'), 'utf8');

assert.match(html, /equipment-affix-policy\.js/, 'affix policy loads before the main game script');
assert.match(html, /world\/f068f8b5f2cdc3d7268f008e3c815db9e1267318\/style\.css/, 'the affix UI stylesheet is pinned to its immutable commit');
assert.match(html, /world\/c7dbee1fbc6b016c20fd3f9cf901eade5b970302\/script\.js/, 'the affix UI renderer is pinned to the current immutable commit');
assert.match(source, /equipmentAffixMigrationVersion !== 'green-affix-v1'/, 'legacy saves receive the affix compatibility migration');
assert.match(source, /EquipmentAffixPolicy\.normalizeEquipment\(item\)/, 'inventory and equipped items are normalized on load');
assert.match(source, /EquipmentAffixPolicy\.getEquippedAffixStats\(progress\.equipment\)/, 'stats read only the equipped item collection');
assert.match(source, /equipment\.maxHpPercent/, 'maximum-health affixes feed the character calculation');
assert.match(source, /equipment\.defensePercent/, 'defense affixes feed the character calculation');
assert.match(source, /equipment\.criticalChance/, 'critical chance affixes feed the character calculation');
assert.match(source, /equipment\.attackSpeedPercent/, 'attack-speed affixes feed the character calculation');
assert.match(source, /EquipmentAffixPolicy\.formatAffix\(entry\)/, 'inventory, comparison and worn views share the affix text renderer');
assert.match(source, /function equipmentDetailsHtml\(item\)/, 'equipment inventory rows use a dedicated details renderer');
assert.match(source, /equipment-affix-title">裝備詞綴/, 'the affix section has a clear title');
assert.match(source, /source === '固定'/, 'affixes expose fixed and random source labels');
assert.match(source, /equipment-affix-value/, 'affix values have a dedicated emphasis element');
assert.match(appCss, /\.equipment-affix-section\{[^}]*border-top:/, 'base stats and affixes are separated visually');
assert.match(appCss, /\.equipment-affix-line\{[^}]*grid-template-columns:/, 'each affix renders on its own aligned line');
assert.match(appCss, /\.equipment-affix-value\{[^}]*font-weight:900/, 'affix values use strong emphasis');
assert.match(source, /affixes: item\.affixes \|\| \[\]/, 'stacking distinguishes equipment with different affixes');
assert.doesNotMatch(source, /equipmentScore|equipmentValue|評分/, 'inventory and comparison no longer expose equipment scores');
assert.doesNotMatch(gameCss, /equipment-score|score-difference/, 'removed score UI has no stale styles');
assert.doesNotMatch(source, /class="item-quality"/, 'inventory, comparison and equipped slots identify quality by frame color instead of text');
assert.match(gameCss, /\.inventory-item\.quality-excellent,.equipment-frame\.quality-excellent\{border-color:#35d778!important/, 'green equipment uses a strong green inventory and equipment frame');
assert.match(html, /inventory-sale-policy\.js[\s\S]*script\.js/, 'sale policy loads before inventory integration');
assert.match(html, /id="sell-confirm-modal"/, 'batch selling has a dedicated confirmation dialog');
assert.match(source, /data-select-common-equipment>勾選全部白色裝備/, 'inventory exposes one-click common equipment selection');
assert.match(source, /InventorySalePolicy\.isCommonEquipment\(item\)/, 'common equipment selection uses the shared quality policy');
assert.doesNotMatch(source, /data-select-unusable-junk|selectUnusableJunkEquipment/, 'obsolete unusable junk quick selection is removed');
assert.match(source, /InventorySalePolicy\.summarizeSelection/, 'selection count and expected gold are recalculated during render');
assert.match(source, /InventorySalePolicy\.sellSelection/, 'confirmed sales use the shared atomic sale policy');
assert.doesNotMatch(source, /data-toggle-junk-ids|data-scrap-ids|toggleEquipmentJunkMark/, 'equipment rows no longer show per-item sale or junk-mark controls');
assert.doesNotMatch(source, /enhanceEquipment|enhancementRules|data-enhance-slot|enhancementBonus/, 'equipment enhancement rules and UI are fully removed');

console.log('equipment-affix-integration: assertions passed');
