const assert=require('node:assert/strict'); const fs=require('node:fs'); const path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'..','script.js'),'utf8'); const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8'); const base=fs.readFileSync(path.join(__dirname,'..','class-skill-policy.js'),'utf8');
assert.match(html,/mage-advancement-policy\.js[\s\S]*script\.js/);
assert.match(base,/shockedVulnerability: \.5[\s\S]*shockedDuration: 4/);
assert.match(source,/job === 'mage'[\s\S]*MageAdvancementPolicy\.getSkills/);
assert.match(source,/getMageShockState\(index, attacker\)[\s\S]*\? 1\.5 : 1/);
assert.match(source,/'arcane-missile': 'arcane'[\s\S]*'arcane-torrent': 'arcane'/);
assert.match(source,/MageAdvancementPolicy\.resolveKill/);
assert.match(source,/getElementalBurstParts[\s\S]*part\.element[\s\S]*recordBonusDamage/);
assert.match(source,/extendElementalCollapseStatuses[\s\S]*shock\.until \+= 1000[\s\S]*shock\.extended = true/);
assert.match(source,/skillEffect\.transformPowerMultiplier[\s\S]*stormFollowupDamage/);
assert.match(source,/stormTargetMultiplier[\s\S]*multiTargetBonusPerTarget[\s\S]*secondDamage \* stormTargetMultiplier/);
assert.match(source,/rollStormElements[\s\S]*applyElementalStormStatus/);
assert.match(source,/addElementMark[\s\S]*reduceLongestElementCooldown/);
assert.match(source,/finishResonance[\s\S]*aliveEnemyIndexesByAge\(\)\.slice\(0, release\.targets \|\| 1\)[\s\S]*attackKind: 'resonance'/);
assert.match(source,/skill\.id === 'arcane-missile'[\s\S]*skillEffect\.missilePower[\s\S]*addArcaneMark/);
assert.match(source,/consumeArcaneMark[\s\S]*sourceSkill: 'arcane-mark-explosion'/);
assert.doesNotMatch(source,/skillEffect\.repeatChance/,'the removed random fifth missile is not part of formal combat');
assert.match(source,/getArcaneDamageMultiplier\(attacker, options\.sourceSkill\)/);
assert.match(source,/suppressesBaseElementEffects\(member, skill\.id\)/);
assert.match(source,/getArcaneCooldownMultiplier\(member\)[\s\S]*skillCooldownMultiplier/);
assert.doesNotMatch(source,/castArcaneCharge\(member/,'formal combat no longer accumulates legacy Arcane Charge stacks');
assert.match(source,/resolveArcaneTorrentMana\(member,skillEffect,hits\.length\)/);
assert.doesNotMatch(source,/MageAdvancementPolicy\.advanceOtherCooldowns/);
assert.match(source,/getMaxManaBonus[\s\S]*getManaBonuses/);
console.log('mage-advancement-integration: assertions passed');
