const assert=require('node:assert/strict'); const fs=require('node:fs'); const path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'..','script.js'),'utf8'); const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8'); const base=fs.readFileSync(path.join(__dirname,'..','class-skill-policy.js'),'utf8');
assert.match(html,/mage-advancement-policy\.js[\s\S]*script\.js/);
assert.match(base,/shockedVulnerability: \.5[\s\S]*shockedDuration: 4/);
assert.match(source,/job === 'mage'[\s\S]*MageAdvancementPolicy\.getSkills/);
assert.match(source,/getMageShockState\(index, attacker\)[\s\S]*\? 1\.5 : 1/);
assert.match(source,/'arcane-missile': 'arcane'[\s\S]*'arcane-torrent': 'arcane'/);
assert.match(source,/MageAdvancementPolicy\.resolveKill/);
assert.match(source,/getElementalBurstParts[\s\S]*part\.element[\s\S]*recordBonusDamage/);
assert.match(source,/extendElementalCollapseStatuses[\s\S]*shock\.until \+= 1000[\s\S]*shock\.extended = true/);
assert.match(source,/skillEffect\.transformPowerMultiplier[\s\S]*stormFollowupDamage/);
assert.match(source,/rollStormElements[\s\S]*applyElementalStormStatus/);
assert.match(source,/addElementMark[\s\S]*reduceLongestElementCooldown/);
assert.match(source,/finishResonance[\s\S]*attackKind: 'resonance'/);
assert.match(source,/repeatChance[\s\S]*recordArcaneRepeat/);
assert.match(source,/castArcaneCharge[\s\S]*arcaneCharge\.noCooldown/);
assert.match(source,/resolveArcaneTorrentMana\(member,skillEffect,hits\.length\)/);
assert.doesNotMatch(source,/MageAdvancementPolicy\.advanceOtherCooldowns/);
assert.match(source,/getMaxManaBonus[\s\S]*getManaBonuses/);
console.log('mage-advancement-integration: assertions passed');
