const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const script = fs.readFileSync(path.join(__dirname, '..', 'script.js'), 'utf8');
const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
const layoutCss = fs.readFileSync(path.join(__dirname, '..', 'styles', 'mmorpg-layout.css'), 'utf8');

assert.match(html, /party-policy\.js[\s\S]*script\.js/, 'party policy loads before the game script');
assert.match(html, /id="party-modal"/, 'party management modal exists');
assert.match(html, /id="battle-party-status"/, 'battle party status exists');
assert.match(html, /mmorpg-layout\.css\?v=20260802-party-resource-bars-v42/, 'party bar fix uses a fresh stylesheet cache key');
assert.match(layoutCss, /\.battle-header \.party-mini-track[\s\S]*max-height: 4px !important/, 'party tracks cannot stretch beyond their compact row');
assert.match(layoutCss, /\.battle-header \.party-mini-track > i[\s\S]*position: absolute[\s\S]*max-height: 4px !important/, 'party bar fills remain constrained to the track');
assert.match(script, /PartyPolicy\.normalizeParty/, 'old saves receive normalized party data');
assert.match(script, /activeMemberIds/, 'active party member ids are persisted');
assert.match(script, /function createBattlePartyMember/, 'each active character receives an independent runtime record');
assert.match(script, /skillCooldowns: \{\}/, 'each member owns skill cooldowns');
assert.match(script, /nextAttackAt: now/, 'each member owns an attack timer');
assert.match(script, /const PARTY_REVIVE_DELAY_MS = 10000/, 'teammate revival waits ten seconds');
assert.match(script, /member\.reviveAt = member\.isMain \? null : now \+ PARTY_REVIVE_DELAY_MS/, 'only defeated teammates receive an automatic revive timer');
assert.match(script, /progress\.potions -= 1[\s\S]*removePotionItem\(progress\)[\s\S]*PARTY_REVIVE_HEALTH_RATIO/, 'revival consumes the main character healing potion and restores configured health');
assert.match(script, /reviveSeconds > 0 \? `\$\{reviveSeconds\} 秒後復活` : '等待治癒藥水'/, 'party status shows the revive countdown and missing-potion state');
assert.match(script, /PartyPolicy\.scheduleNextAttack\(member, now, member\.attackSpeed, exhaustedMultiplier\)/, 'attack timing uses each member attack speed');
assert.match(script, /chooseRandomAliveMember\(battle\.partyMembers/, 'monsters choose among living party members');
assert.match(script, /PartyPolicy\.isPartyDefeated\(battle\.partyMembers\)/, 'failure requires the whole party to be defeated');
assert.match(script, /rewardedEnemyIndexes/, 'enemy rewards are guarded against duplicate processing');
assert.match(script, /enemyNextAttackAt\[enemyIndex\]/, 'each monster retains an independent attack timer');
assert.match(script, /persistPartyRuntimeState/, 'runtime party state is included in saves');
assert.match(script, /const PARTY_DEBUG = false/, 'party debug mode is centrally controlled and disabled for normal play');
assert.match(script, /battleLogEntries\.filter\(\(entry\) => PARTY_DEBUG \|\| !entry\.partyDebug\)/, 'disabled party debug entries cannot leak into the player combat log');
assert.match(script, /const teammates = \(battle\.partyMembers \|\| \[\]\)\.filter\(\(member\) => !member\.isMain\)/, 'battle party status excludes the main character');
assert.match(script, /container\.classList\.toggle\('hidden', teammates\.length === 0\)/, 'solo parties hide the empty teammate status area');
assert.match(html, /crafting-policy\.js/, 'crafting policy loads before the game integration');
assert.match(script, /logPartyDebug\('普通攻擊'/, 'debug logs include normal attacks');
const manaExhaustionBody = script.match(/function updatePartyMemberManaExhaustion\(member\) \{([\s\S]*?)\n\}/)?.[1] || '';
assert.doesNotMatch(manaExhaustionBody, /enemy|rewardKey|earnedXp|earnedGold|accountDrops/, 'mana state updates cannot throw on unrelated reward variables before normal attacks');
assert.match(manaExhaustionBody, /!member\.manaExhausted && ratio <= \.15[\s\S]*member\.isMain[\s\S]*useManaPotion\(\)/, 'the main character automatically uses one mana potion when entering mana exhaustion');
assert.doesNotMatch(manaExhaustionBody, /else if \(member\.manaExhausted[\s\S]*useManaPotion\(\)/, 'an already exhausted character does not repeatedly consume mana potions');
assert.match(script, /updatePartyMemberResource\(member, now\)[\s\S]*processPartyMemberAttacks\(now\)/, 'resource updates complete before the independent normal attack pass');
assert.match(script, /PlainsDepthsPolicy\.resolveActiveSkill/, 'plains depths active skills resolve on monster attack turns');
assert.match(script, /PlainsDepthsPolicy\.applyBlackstoneAura/, 'alive blackstone monsters feed the shared attack and defense aura');
assert.match(script, /enemy\.id === 'wanderingBlackKnight'[\s\S]*COUNTER_DAMAGE_MULTIPLIER/, 'black knight parries trigger counterattack damage');
assert.match(script, /blackstoneRoarUntil/, 'blackstone leader roar has battle-scoped duration state');
assert.match(script, /logPartyDebug\('技能施放'/, 'debug logs include skill casts and resources');
assert.match(script, /logPartyDebug\('怪物選擇隊員'/, 'debug logs include monster target selection');
assert.match(script, /logPartyDebug\('死亡事件'/, 'debug logs include member deaths');
assert.match(script, /logPartyDebug\('掉落事件'/, 'debug logs include rewards and drops');
assert.match(script, /logPartyDebug\('戰鬥失敗事件'/, 'debug logs include full-party defeat');
assert.match(script, /PartyPolicy\.claimEnemyReward/, 'live reward processing uses the tested duplicate guard');
assert.match(script, /PartyPolicy\.canMemberAttack/, 'live attacks use the tested per-member timer guard');
assert.match(script, /clearInterval\(battleTimer\)[\s\S]*clearInterval\(skillTimer\)[\s\S]*clearInterval\(enemyAttackTimer\)[\s\S]*setInterval\(autoSkillTick, 100\)[\s\S]*setInterval\(battleTick, 100\)[\s\S]*setInterval\(enemyAttackTick, 100\)/, 'map entry replaces all three combat loops before registering new ones');

console.log('party-integration: assertions passed');
