const assert=require('node:assert/strict');
const policy=require('../priest-advancement-policy.js');
assert.deepEqual(Object.values(policy.ADVANCED_CLASSES).map(x=>x.id),['holy-priest','battle-priest']);
assert.equal(policy.getSkills('holy-priest').length,4);
assert.equal(policy.getSkills('battle-priest').length,4);
assert.deepEqual([policy.getEffect('light-fountain',6).healPower,policy.getEffect('light-fountain',6).lowHpShield,policy.getSkill('light-fountain').manaCost],[1.1,.08,34]);
assert.deepEqual([policy.getEffect('guardian-sanctuary',6).damageReduction,policy.getEffect('guardian-sanctuary',6).tickHealPower,policy.getEffect('guardian-sanctuary',6).cleanseOnCast],[.15,.25,true]);
assert.equal(policy.getEffect('prayer-of-life',6).guardianIcd,120);
assert.equal(policy.getEffect('light-echo',6).extraTargets,2);
assert.deepEqual([policy.getEffect('holy-smite',6).power,policy.getEffect('holy-smite',6).damageHealing,policy.getSkill('holy-smite').manaCost],[2.45,.15,24]);
assert.deepEqual([policy.getEffect('holy-storm',6).power,policy.getEffect('holy-storm',6).partyHealPerHit,policy.getEffect('holy-storm',6).attackSpeed],[1.05,.05,.08]);
const member={progress:{advancedClass:'battle-priest',skillLevels:{'priest:holy-faith':6,'priest:fanatical-faith':6}}};
policy.addFaith(member,1000);policy.addFaith(member,1000);policy.addFaith(member,1000);
const faith=policy.getFaithBonuses(member,2000);assert.deepEqual({...faith,magicDamage:Number(faith.magicDamage.toFixed(2))},{stacks:3,healing:.09,selfDamageReduction:.06,magicDamage:.21,cooldownSpeed:.10});
assert.equal(policy.getFaithStacks(member,7000),0,'faith expires and clears at six seconds');
const priest={progress:{advancedClass:'holy-priest',skillLevels:{'priest:prayer-of-life':6}}};
const first={alive:false,currentHp:0,maxHp:1000},second={alive:false,currentHp:0,maxHp:1000},party={};
assert.equal(policy.trySacredGuardian(priest,first,party,1000),true);assert.equal(first.currentHp,151);assert.equal(party.sacredGuardianReadyAt,121000);
assert.equal(policy.trySacredGuardian(priest,second,party,5000),false,'the 120-second cooldown is shared by the whole party');
assert.equal(policy.trySacredGuardian(priest,second,party,121000),true);
const normalized=policy.normalizeSkillLevels({'priest:light-fountain':6,'priest:guardian-sanctuary':6},'holy-priest');
assert.deepEqual([normalized['priest:light-fountain'],normalized['priest:guardian-sanctuary']],[6,5]);
console.log('priest-advancement-policy: assertions passed');
