'use strict';
const assert=require('node:assert/strict');const bloodwar=require('../bloodwar-wastes-policy.js');const policy=require('../skullcrusher-war-camp-policy.js');
assert.equal(policy.getSkill('blood-rage'),bloodwar.getSkill('blood-rage'));assert.equal(policy.getSkill('warblood-totem'),bloodwar.getSkill('warblood-totem'));assert.deepEqual(policy.getEnemySkills('skullcrusher-berserker'),['blood-rage']);
const guard=policy.createState();assert.deepEqual(policy.getCombatMultipliers('skullcrusher-heavy-guard',guard),{attack:1,attackSpeed:1,defense:1.3,damageReduction:0});assert.equal(policy.getHeavyGuardCriticalDamageMultiplier(true),.8);assert.equal(policy.getHeavyGuardCriticalDamageMultiplier(false),1);policy.recordHeavyGuardCritical(guard,100,80);assert.equal(guard.telemetry.heavyGuardCriticalDamagePrevented,20);
const wolf=policy.createState(1000);assert.deepEqual(policy.resolveScheduledActions('skullcrusher-wolf-rider',wolf,2999),[]);assert.deepEqual(policy.resolveScheduledActions('skullcrusher-wolf-rider',wolf,3000).map(x=>x.id),['warwolf-assault']);assert.equal(wolf.nextSkillAt['warwolf-assault'],13000);const front={id:'front',alive:true,isFrontline:true},backA={id:'a',alive:true},backB={id:'b',alive:true};assert.equal(policy.chooseWarwolfTarget([front,backA,backB],front,.9).id,'b');assert.equal(policy.chooseWarwolfTarget([front],front,.5),front);policy.recordWarwolfTarget(wolf,backA);policy.recordWolfArmorBreakCoverage(wolf,5000);assert.equal(wolf.telemetry.wolfAssaultBacklineTargets,1);assert.equal(wolf.telemetry.wolfArmorBreakActiveMs,5000);
const champion=policy.createState();assert.deepEqual(policy.updateThresholds('skullcrusher-champion',champion,25,100).map(x=>x.threshold),[.75,.5,.25]);assert.equal(champion.unyieldingStacks,3);assert.deepEqual(policy.getCombatMultipliers('skullcrusher-champion',champion),{attack:1.18,attackSpeed:1,defense:1,damageReduction:.15});assert.deepEqual(policy.updateThresholds('skullcrusher-champion',champion,90,100),[]);assert.deepEqual(policy.updateThresholds('skullcrusher-champion',champion,10,100),[]);assert.deepEqual(champion.telemetry.championThresholds,{75:1,50:1,25:1});
const boss=policy.createState();for(let i=1;i<=5;i++)policy.recordOtherEnemyDeath(boss,{enemyId:`enemy-${i}`,atMs:i*1000});assert.equal(boss.fallenRageStacks,4);assert.equal(boss.telemetry.fallenRageSources.length,4);assert.equal(boss.telemetry.fallenRageIgnoredDeaths,1);assert.equal(policy.recordOtherEnemyDeath(boss,{enemyId:'enemy-1',atMs:9000}),false,'one death cannot trigger twice');assert.deepEqual(policy.updateThresholds('skullcrusher-great-chieftain',boss,29,100,10000).map(x=>x.id),['skullcrusher-overlord']);assert.deepEqual(policy.getCombatMultipliers('skullcrusher-great-chieftain',boss),{attack:1.44,attackSpeed:1.2,defense:1,damageReduction:.15});assert.deepEqual(policy.updateThresholds('skullcrusher-great-chieftain',boss,90,100,11000),[]);assert.equal(policy.recordOtherEnemyDeath(policy.createState(),{enemyId:'x',bossAlive:false}),false);
assert.deepEqual(policy.getSkill('chieftain-earthsplitter').debuffs.map(x=>[x.type,x.value,x.durationMs]),[['defense-down',.15,5000],['healing-received-down',.15,5000]]);assert.deepEqual({damage:policy.getSkill('champion-slash').damageMultiplier,ignore:policy.getSkill('champion-slash').defenseIgnore},{damage:2.1,ignore:.2});
console.log('skullcrusher-war-camp-policy: assertions passed');
